In [6]:
import os
from datetime import datetime

def rename_images_to_citra(folder_path):
    
    for file in os.listdir(folder_path):
        
        if file.endswith(".jpg"):
            
            try:
                name = file.replace(".jpg","")
                
                # parse original format
                dt = datetime.strptime(name, "%Y-%m-%d_%H-%M")
                
                # convert to citra format with seconds = 01
                new_name = f"citra_{dt.strftime('%Y-%m-%d_%H%M')}01.jpg"
                
                old_path = os.path.join(folder_path, file)
                new_path = os.path.join(folder_path, new_name)
                
                os.rename(old_path, new_path)
                
            except Exception as e:
                print("Skipping:", file, e)


folder = r"F:\strwaberry images\Front_row_with_text"

rename_images_to_citra(folder)

print("Renaming completed")

Renaming completed

In [8]:
import os
from datetime import datetime

def get_min_max_timestamp(folder_path):
    timestamps = []

    for file in os.listdir(folder_path):
        if file.endswith(".jpg"):
            try:
                # remove prefix and extension
                name = file.replace("citra_", "").replace(".jpg", "")
                
                # convert to datetime
                dt = datetime.strptime(name, "%Y-%m-%d_%H%M%S")
                timestamps.append(dt)

            except Exception as e:
                print(f"Skipping file {file}: {e}")

    if not timestamps:
        return None, None

    return min(timestamps), max(timestamps)


folder = r"F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images"

min_time, max_time = get_min_max_timestamp(folder)

print("Earliest Timestamp:", min_time)
print("Latest Timestamp:", max_time)

Earliest Timestamp: 2025-12-12 15:00:01
Latest Timestamp: 2025-12-21 11:15:01

In [ ]:
import os
import pandas as pd
from datetime import datetime

def create_timestamp_excel(folder_path, output_excel):
    records = []

    for file in os.listdir(folder_path):
        if file.endswith(".jpg"):
            try:
                name = file.replace(".jpg", "")
                dt = datetime.strptime(name, "%Y-%m-%d_%H-%M")

                records.append({
                    "filename": file,
                    "date": dt.date(),
                    "time": dt.time(),
                    "timestamp": dt
                })

            except Exception as e:
                print(f"Skipping {file}: {e}")

    df = pd.DataFrame(records)

    # sort by time
    df = df.sort_values("timestamp")

    # save excel
    df.to_excel(output_excel, index=False)

    print("Excel saved to:", output_excel)


folder = r"F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_2\preprocessed_images"
output = r"F:\timestamps.xlsx"

create_timestamp_excel(folder, output)

In [9]:
import pandas as pd

def filter_datetime_excel(input_excel, output_excel, start_time, end_time):

    # read excel
    df = pd.read_excel(input_excel)

    # convert Datetime column to datetime format
    df["Date Time"] = pd.to_datetime(df["Date Time"], format="%d-%m-%Y %H:%M")

    # define time range
    start = pd.to_datetime(start_time)
    end = pd.to_datetime(end_time)

    # filter rows
    filtered_df = df[(df["Date Time"] >= start) & (df["Date Time"] <= end)]

    # save new excel
    filtered_df.to_excel(output_excel, index=False)

    print("Filtered Excel saved at:", output_excel)


input_excel = r"FAWN_2025.xlsx"
output_excel = r"Front_down_1_plants_weather_mapped.xlsx"

# start_time = "2025-12-12 16:30:01"
# end_time = "2026-01-18 18:45:01"

filter_datetime_excel(input_excel, output_excel, start_time=min_time, end_time=max_time)

Filtered Excel saved at: Front_down_1_plants_weather_mapped.xlsx

In [14]:
min_time,max_time

(datetime.datetime(2025, 12, 12, 15, 0, 1),
 datetime.datetime(2025, 12, 21, 11, 15, 1))

In [ ]:
import pandas as pd

def filter_datetime_excel(input_excel, output_excel, start_time, end_time):

    # read excel
    df = pd.read_excel(input_excel)

    # convert Datetime column to datetime format
    df["Date Time"] = pd.to_datetime(df["Date Time"], format="%d-%m-%Y %H:%M")

    # define time range
    start = pd.to_datetime(start_time)
    end = pd.to_datetime(end_time)

    # filter rows
    filtered_df = df[(df["Date Time"] >= start) & (df["Date Time"] <= end)]

    # save new excel
    filtered_df.to_excel(output_excel, index=False)

    print("Filtered Excel saved at:", output_excel)


input_excel = r"FAWN_2026.xlsx"
output_excel = r"front_down_1_plants_weather_mapped_2026.xlsx"

# start_time = "2025-12-12 15:00:01"
# end_time = "2026-01-18 18:45:01"

filter_datetime_excel(input_excel, output_excel, start_time=min_time, end_time=max_time)

Filtered Excel saved at: front_down_1_plants_weather_mapped_2026.xlsx

In [23]:
import os
import pandas as pd
from datetime import datetime

def map_images_to_excel(excel_path, image_folder, output_excel):

    # read excel
    df = pd.read_excel(excel_path)
    df["Date Time"] = pd.to_datetime(df["Date Time"], format="%d-%m-%Y %H:%M")

    image_data = []

    # read image timestamps
    for file in os.listdir(image_folder):
        if file.endswith(".jpg"):

            try:
                name = file.replace("citra_", "").replace(".jpg", "")
                img_time = datetime.strptime(name, "%Y-%m-%d_%H%M%S")

                image_data.append((img_time, file))

            except:
                try:
                    name = file.replace(".jpg", "")
                    img_time = datetime.strptime(name, "%Y-%m-%d_%H-%M")

                    image_data.append((img_time, file))
                except:
                    continue

    # convert to dataframe
    img_df = pd.DataFrame(image_data, columns=["img_time", "image_name"])
    img_df = img_df.sort_values("img_time")

    # map nearest timestamp
    df["image_name"] = df["Date Time"].apply(
        lambda x: img_df.iloc[(img_df["img_time"] - x).abs().argsort()[:1]]["image_name"].values[0]
    )

    # save new excel
    df.to_excel(output_excel, index=False)

    print("Mapped Excel saved:", output_excel)


excel_path = r"Front_down_1_plants_weather_mapped.xlsx"
image_folder = r"F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images"
output_excel = r"Front_images_mapped_images_down_1.xlsx"

map_images_to_excel(excel_path, image_folder, output_excel)

Mapped Excel saved: Front_images_mapped_images_down_1.xlsx

In [28]:
import os
import pandas as pd
from datetime import datetime

def map_images_with_tolerance(excel_path, image_folder, output_excel):

    # read excel
    df = pd.read_excel(excel_path)
    df["Date Time"] = pd.to_datetime(df["Date Time"])
    df = df.sort_values("Date Time")

    image_data = []

    # read image timestamps
    for file in os.listdir(image_folder):

        if file.endswith(".jpg"):
            try:
                name = file.replace("citra_", "").replace(".jpg", "")
                img_time = datetime.strptime(name, "%Y-%m-%d_%H%M%S")
            except:
                try:
                    name = file.replace(".jpg", "")
                    img_time = datetime.strptime(name, "%Y-%m-%d_%H-%M")
                except:
                    continue

            image_data.append([img_time, file])

    img_df = pd.DataFrame(image_data, columns=["img_time", "image_name"])
    img_df = img_df.sort_values("img_time")
    print(image_data)

    # nearest merge with tolerance ±5 minutes
    mapped = pd.merge_asof(
        df,
        img_df,
        left_on="Date Time",
        right_on="img_time",
        direction="nearest",
        tolerance=pd.Timedelta("5min")
    )

    mapped.drop(columns=["img_time"], inplace=True)

    mapped.to_excel(output_excel, index=False)

    print("Saved:", output_excel)

# excel_path = r"down_plants_weather_mapped.xlsx"
# image_folder = r"back row upated with text\Cropped_Images\down_2\preprocessed_images"
# output_excel = r"images_mapped_images_down.xlsx"

excel_path = r"Front_down_1_plants_weather_mapped.xlsx"
image_folder = r"F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images"
output_excel = r"Front_images_mapped_images_down_1.xlsx"

map_images_with_tolerance(excel_path, image_folder, output_excel)

[[datetime.datetime(2025, 12, 12, 15, 0, 1), 'citra_2025-12-12_150001.jpg'], [datetime.datetime(2025, 12, 13, 6, 0, 1), 'citra_2025-12-13_060001.jpg'], [datetime.datetime(2025, 12, 13, 6, 15, 1), 'citra_2025-12-13_061501.jpg'], [datetime.datetime(2025, 12, 13, 6, 30, 1), 'citra_2025-12-13_063001.jpg'], [datetime.datetime(2025, 12, 13, 6, 45, 1), 'citra_2025-12-13_064501.jpg'], [datetime.datetime(2025, 12, 13, 7, 0, 1), 'citra_2025-12-13_070001.jpg'], [datetime.datetime(2025, 12, 13, 7, 15, 1), 'citra_2025-12-13_071501.jpg'], [datetime.datetime(2025, 12, 13, 7, 30, 1), 'citra_2025-12-13_073001.jpg'], [datetime.datetime(2025, 12, 13, 7, 45, 1), 'citra_2025-12-13_074501.jpg'], [datetime.datetime(2025, 12, 13, 8, 0, 1), 'citra_2025-12-13_080001.jpg'], [datetime.datetime(2025, 12, 13, 8, 15, 1), 'citra_2025-12-13_081501.jpg'], [datetime.datetime(2025, 12, 13, 8, 30, 1), 'citra_2025-12-13_083001.jpg'], [datetime.datetime(2025, 12, 13, 8, 45, 1), 'citra_2025-12-13_084501.jpg'], [datetime.datetime(2025, 12, 13, 9, 0, 1), 'citra_2025-12-13_090001.jpg'], [datetime.datetime(2025, 12, 13, 9, 15, 1), 'citra_2025-12-13_091501.jpg'], [datetime.datetime(2025, 12, 13, 9, 30, 1), 'citra_2025-12-13_093001.jpg'], [datetime.datetime(2025, 12, 13, 9, 45, 1), 'citra_2025-12-13_094501.jpg'], [datetime.datetime(2025, 12, 13, 10, 0, 1), 'citra_2025-12-13_100001.jpg'], [datetime.datetime(2025, 12, 13, 10, 15, 1), 'citra_2025-12-13_101501.jpg'], [datetime.datetime(2025, 12, 13, 10, 30, 1), 'citra_2025-12-13_103001.jpg'], [datetime.datetime(2025, 12, 13, 10, 45, 1), 'citra_2025-12-13_104501.jpg'], [datetime.datetime(2025, 12, 13, 11, 0, 1), 'citra_2025-12-13_110001.jpg'], [datetime.datetime(2025, 12, 13, 11, 15, 1), 'citra_2025-12-13_111501.jpg'], [datetime.datetime(2025, 12, 13, 11, 30, 1), 'citra_2025-12-13_113001.jpg'], [datetime.datetime(2025, 12, 13, 11, 45, 1), 'citra_2025-12-13_114501.jpg'], [datetime.datetime(2025, 12, 13, 12, 0, 1), 'citra_2025-12-13_120001.jpg'], [datetime.datetime(2025, 12, 13, 12, 15, 1), 'citra_2025-12-13_121501.jpg'], [datetime.datetime(2025, 12, 13, 12, 30, 1), 'citra_2025-12-13_123001.jpg'], [datetime.datetime(2025, 12, 13, 12, 45, 1), 'citra_2025-12-13_124501.jpg'], [datetime.datetime(2025, 12, 13, 13, 0, 1), 'citra_2025-12-13_130001.jpg'], [datetime.datetime(2025, 12, 13, 13, 15, 1), 'citra_2025-12-13_131501.jpg'], [datetime.datetime(2025, 12, 13, 13, 30, 1), 'citra_2025-12-13_133001.jpg'], [datetime.datetime(2025, 12, 13, 13, 45, 1), 'citra_2025-12-13_134501.jpg'], [datetime.datetime(2025, 12, 13, 14, 0, 1), 'citra_2025-12-13_140001.jpg'], [datetime.datetime(2025, 12, 13, 14, 15, 1), 'citra_2025-12-13_141501.jpg'], [datetime.datetime(2025, 12, 13, 14, 30, 1), 'citra_2025-12-13_143001.jpg'], [datetime.datetime(2025, 12, 13, 14, 45, 1), 'citra_2025-12-13_144501.jpg'], [datetime.datetime(2025, 12, 13, 15, 0, 1), 'citra_2025-12-13_150001.jpg'], [datetime.datetime(2025, 12, 14, 6, 0, 1), 'citra_2025-12-14_060001.jpg'], [datetime.datetime(2025, 12, 14, 6, 15, 1), 'citra_2025-12-14_061501.jpg'], [datetime.datetime(2025, 12, 14, 6, 30, 1), 'citra_2025-12-14_063001.jpg'], [datetime.datetime(2025, 12, 14, 6, 45, 1), 'citra_2025-12-14_064501.jpg'], [datetime.datetime(2025, 12, 14, 7, 0, 1), 'citra_2025-12-14_070001.jpg'], [datetime.datetime(2025, 12, 14, 7, 15, 1), 'citra_2025-12-14_071501.jpg'], [datetime.datetime(2025, 12, 14, 7, 30, 1), 'citra_2025-12-14_073001.jpg'], [datetime.datetime(2025, 12, 14, 7, 45, 1), 'citra_2025-12-14_074501.jpg'], [datetime.datetime(2025, 12, 14, 8, 0, 1), 'citra_2025-12-14_080001.jpg'], [datetime.datetime(2025, 12, 14, 8, 15, 1), 'citra_2025-12-14_081501.jpg'], [datetime.datetime(2025, 12, 14, 8, 30, 1), 'citra_2025-12-14_083001.jpg'], [datetime.datetime(2025, 12, 14, 8, 45, 1), 'citra_2025-12-14_084501.jpg'], [datetime.datetime(2025, 12, 14, 9, 0, 1), 'citra_2025-12-14_090001.jpg'], [datetime.datetime(2025, 12, 14, 9, 15, 1), 'citra_2025-12-14_091501.jpg'], [datetime.datetime(2025, 12, 14, 9, 30, 1), 'citra_2025-12-14_093001.jpg'], [datetime.datetime(2025, 12, 14, 9, 45, 1), 'citra_2025-12-14_094501.jpg'], [datetime.datetime(2025, 12, 14, 10, 0, 1), 'citra_2025-12-14_100001.jpg'], [datetime.datetime(2025, 12, 14, 10, 15, 1), 'citra_2025-12-14_101501.jpg'], [datetime.datetime(2025, 12, 14, 10, 30, 1), 'citra_2025-12-14_103001.jpg'], [datetime.datetime(2025, 12, 14, 10, 45, 1), 'citra_2025-12-14_104501.jpg'], [datetime.datetime(2025, 12, 14, 11, 0, 1), 'citra_2025-12-14_110001.jpg'], [datetime.datetime(2025, 12, 14, 11, 15, 1), 'citra_2025-12-14_111501.jpg'], [datetime.datetime(2025, 12, 14, 11, 30, 1), 'citra_2025-12-14_113001.jpg'], [datetime.datetime(2025, 12, 14, 11, 45, 1), 'citra_2025-12-14_114501.jpg'], [datetime.datetime(2025, 12, 14, 12, 0, 1), 'citra_2025-12-14_120001.jpg'], [datetime.datetime(2025, 12, 14, 12, 15, 1), 'citra_2025-12-14_121501.jpg'], [datetime.datetime(2025, 12, 14, 12, 30, 1), 'citra_2025-12-14_123001.jpg'], [datetime.datetime(2025, 12, 14, 12, 45, 1), 'citra_2025-12-14_124501.jpg'], [datetime.datetime(2025, 12, 14, 13, 0, 1), 'citra_2025-12-14_130001.jpg'], [datetime.datetime(2025, 12, 14, 13, 15, 1), 'citra_2025-12-14_131501.jpg'], [datetime.datetime(2025, 12, 14, 13, 30, 1), 'citra_2025-12-14_133001.jpg'], [datetime.datetime(2025, 12, 14, 13, 45, 1), 'citra_2025-12-14_134501.jpg'], [datetime.datetime(2025, 12, 14, 14, 0, 1), 'citra_2025-12-14_140001.jpg'], [datetime.datetime(2025, 12, 14, 14, 15, 1), 'citra_2025-12-14_141501.jpg'], [datetime.datetime(2025, 12, 14, 14, 30, 1), 'citra_2025-12-14_143001.jpg'], [datetime.datetime(2025, 12, 14, 14, 45, 1), 'citra_2025-12-14_144501.jpg'], [datetime.datetime(2025, 12, 14, 15, 0, 1), 'citra_2025-12-14_150001.jpg'], [datetime.datetime(2025, 12, 15, 6, 0, 1), 'citra_2025-12-15_060001.jpg'], [datetime.datetime(2025, 12, 15, 6, 15, 1), 'citra_2025-12-15_061501.jpg'], [datetime.datetime(2025, 12, 15, 6, 30, 1), 'citra_2025-12-15_063001.jpg'], [datetime.datetime(2025, 12, 15, 6, 45, 1), 'citra_2025-12-15_064501.jpg'], [datetime.datetime(2025, 12, 15, 7, 0, 1), 'citra_2025-12-15_070001.jpg'], [datetime.datetime(2025, 12, 15, 7, 15, 1), 'citra_2025-12-15_071501.jpg'], [datetime.datetime(2025, 12, 15, 7, 30, 1), 'citra_2025-12-15_073001.jpg'], [datetime.datetime(2025, 12, 15, 7, 45, 1), 'citra_2025-12-15_074501.jpg'], [datetime.datetime(2025, 12, 15, 8, 0, 1), 'citra_2025-12-15_080001.jpg'], [datetime.datetime(2025, 12, 15, 8, 15, 1), 'citra_2025-12-15_081501.jpg'], [datetime.datetime(2025, 12, 15, 8, 30, 1), 'citra_2025-12-15_083001.jpg'], [datetime.datetime(2025, 12, 15, 8, 45, 1), 'citra_2025-12-15_084501.jpg'], [datetime.datetime(2025, 12, 15, 9, 0, 1), 'citra_2025-12-15_090001.jpg'], [datetime.datetime(2025, 12, 15, 9, 15, 1), 'citra_2025-12-15_091501.jpg'], [datetime.datetime(2025, 12, 15, 9, 30, 1), 'citra_2025-12-15_093001.jpg'], [datetime.datetime(2025, 12, 15, 9, 45, 1), 'citra_2025-12-15_094501.jpg'], [datetime.datetime(2025, 12, 15, 10, 0, 1), 'citra_2025-12-15_100001.jpg'], [datetime.datetime(2025, 12, 15, 10, 15, 1), 'citra_2025-12-15_101501.jpg'], [datetime.datetime(2025, 12, 15, 10, 30, 1), 'citra_2025-12-15_103001.jpg'], [datetime.datetime(2025, 12, 15, 10, 45, 1), 'citra_2025-12-15_104501.jpg'], [datetime.datetime(2025, 12, 15, 11, 0, 1), 'citra_2025-12-15_110001.jpg'], [datetime.datetime(2025, 12, 15, 11, 15, 1), 'citra_2025-12-15_111501.jpg'], [datetime.datetime(2025, 12, 15, 11, 30, 1), 'citra_2025-12-15_113001.jpg'], [datetime.datetime(2025, 12, 15, 11, 45, 1), 'citra_2025-12-15_114501.jpg'], [datetime.datetime(2025, 12, 15, 12, 0, 1), 'citra_2025-12-15_120001.jpg'], [datetime.datetime(2025, 12, 15, 12, 15, 1), 'citra_2025-12-15_121501.jpg'], [datetime.datetime(2025, 12, 15, 12, 30, 1), 'citra_2025-12-15_123001.jpg'], [datetime.datetime(2025, 12, 15, 12, 45, 1), 'citra_2025-12-15_124501.jpg'], [datetime.datetime(2025, 12, 15, 13, 0, 1), 'citra_2025-12-15_130001.jpg'], [datetime.datetime(2025, 12, 15, 13, 15, 1), 'citra_2025-12-15_131501.jpg'], [datetime.datetime(2025, 12, 15, 13, 30, 1), 'citra_2025-12-15_133001.jpg'], [datetime.datetime(2025, 12, 15, 13, 45, 1), 'citra_2025-12-15_134501.jpg'], [datetime.datetime(2025, 12, 15, 14, 0, 1), 'citra_2025-12-15_140001.jpg'], [datetime.datetime(2025, 12, 15, 14, 15, 1), 'citra_2025-12-15_141501.jpg'], [datetime.datetime(2025, 12, 15, 14, 30, 1), 'citra_2025-12-15_143001.jpg'], [datetime.datetime(2025, 12, 15, 14, 45, 1), 'citra_2025-12-15_144501.jpg'], [datetime.datetime(2025, 12, 15, 15, 0, 1), 'citra_2025-12-15_150001.jpg'], [datetime.datetime(2025, 12, 16, 6, 0, 1), 'citra_2025-12-16_060001.jpg'], [datetime.datetime(2025, 12, 16, 6, 15, 1), 'citra_2025-12-16_061501.jpg'], [datetime.datetime(2025, 12, 16, 6, 30, 1), 'citra_2025-12-16_063001.jpg'], [datetime.datetime(2025, 12, 16, 6, 45, 1), 'citra_2025-12-16_064501.jpg'], [datetime.datetime(2025, 12, 16, 7, 0, 1), 'citra_2025-12-16_070001.jpg'], [datetime.datetime(2025, 12, 16, 7, 15, 1), 'citra_2025-12-16_071501.jpg'], [datetime.datetime(2025, 12, 16, 7, 30, 1), 'citra_2025-12-16_073001.jpg'], [datetime.datetime(2025, 12, 16, 7, 45, 1), 'citra_2025-12-16_074501.jpg'], [datetime.datetime(2025, 12, 16, 8, 0, 1), 'citra_2025-12-16_080001.jpg'], [datetime.datetime(2025, 12, 16, 8, 15, 1), 'citra_2025-12-16_081501.jpg'], [datetime.datetime(2025, 12, 16, 8, 30, 1), 'citra_2025-12-16_083001.jpg'], [datetime.datetime(2025, 12, 16, 8, 45, 1), 'citra_2025-12-16_084501.jpg'], [datetime.datetime(2025, 12, 16, 9, 0, 1), 'citra_2025-12-16_090001.jpg'], [datetime.datetime(2025, 12, 16, 9, 15, 1), 'citra_2025-12-16_091501.jpg'], [datetime.datetime(2025, 12, 16, 9, 30, 1), 'citra_2025-12-16_093001.jpg'], [datetime.datetime(2025, 12, 16, 9, 45, 1), 'citra_2025-12-16_094501.jpg'], [datetime.datetime(2025, 12, 16, 10, 0, 1), 'citra_2025-12-16_100001.jpg'], [datetime.datetime(2025, 12, 16, 10, 15, 1), 'citra_2025-12-16_101501.jpg'], [datetime.datetime(2025, 12, 16, 10, 30, 1), 'citra_2025-12-16_103001.jpg'], [datetime.datetime(2025, 12, 16, 10, 45, 1), 'citra_2025-12-16_104501.jpg'], [datetime.datetime(2025, 12, 16, 11, 0, 1), 'citra_2025-12-16_110001.jpg'], [datetime.datetime(2025, 12, 16, 11, 15, 1), 'citra_2025-12-16_111501.jpg'], [datetime.datetime(2025, 12, 16, 11, 30, 1), 'citra_2025-12-16_113001.jpg'], [datetime.datetime(2025, 12, 16, 11, 45, 1), 'citra_2025-12-16_114501.jpg'], [datetime.datetime(2025, 12, 16, 12, 0, 1), 'citra_2025-12-16_120001.jpg'], [datetime.datetime(2025, 12, 16, 12, 15, 1), 'citra_2025-12-16_121501.jpg'], [datetime.datetime(2025, 12, 16, 12, 30, 1), 'citra_2025-12-16_123001.jpg'], [datetime.datetime(2025, 12, 16, 12, 45, 1), 'citra_2025-12-16_124501.jpg'], [datetime.datetime(2025, 12, 16, 13, 0, 1), 'citra_2025-12-16_130001.jpg'], [datetime.datetime(2025, 12, 16, 13, 15, 1), 'citra_2025-12-16_131501.jpg'], [datetime.datetime(2025, 12, 16, 13, 30, 1), 'citra_2025-12-16_133001.jpg'], [datetime.datetime(2025, 12, 16, 13, 45, 1), 'citra_2025-12-16_134501.jpg'], [datetime.datetime(2025, 12, 16, 14, 0, 1), 'citra_2025-12-16_140001.jpg'], [datetime.datetime(2025, 12, 16, 14, 15, 1), 'citra_2025-12-16_141501.jpg'], [datetime.datetime(2025, 12, 16, 14, 30, 1), 'citra_2025-12-16_143001.jpg'], [datetime.datetime(2025, 12, 16, 14, 45, 1), 'citra_2025-12-16_144501.jpg'], [datetime.datetime(2025, 12, 16, 15, 0, 1), 'citra_2025-12-16_150001.jpg'], [datetime.datetime(2025, 12, 17, 6, 0, 1), 'citra_2025-12-17_060001.jpg'], [datetime.datetime(2025, 12, 17, 6, 15, 1), 'citra_2025-12-17_061501.jpg'], [datetime.datetime(2025, 12, 17, 6, 30, 1), 'citra_2025-12-17_063001.jpg'], [datetime.datetime(2025, 12, 17, 6, 45, 1), 'citra_2025-12-17_064501.jpg'], [datetime.datetime(2025, 12, 17, 7, 0, 1), 'citra_2025-12-17_070001.jpg'], [datetime.datetime(2025, 12, 17, 7, 15, 1), 'citra_2025-12-17_071501.jpg'], [datetime.datetime(2025, 12, 17, 7, 30, 1), 'citra_2025-12-17_073001.jpg'], [datetime.datetime(2025, 12, 17, 7, 45, 1), 'citra_2025-12-17_074501.jpg'], [datetime.datetime(2025, 12, 17, 8, 0, 1), 'citra_2025-12-17_080001.jpg'], [datetime.datetime(2025, 12, 17, 8, 15, 1), 'citra_2025-12-17_081501.jpg'], [datetime.datetime(2025, 12, 17, 8, 30, 1), 'citra_2025-12-17_083001.jpg'], [datetime.datetime(2025, 12, 17, 8, 45, 1), 'citra_2025-12-17_084501.jpg'], [datetime.datetime(2025, 12, 17, 9, 0, 1), 'citra_2025-12-17_090001.jpg'], [datetime.datetime(2025, 12, 17, 9, 15, 1), 'citra_2025-12-17_091501.jpg'], [datetime.datetime(2025, 12, 17, 9, 30, 1), 'citra_2025-12-17_093001.jpg'], [datetime.datetime(2025, 12, 17, 9, 45, 1), 'citra_2025-12-17_094501.jpg'], [datetime.datetime(2025, 12, 17, 10, 0, 1), 'citra_2025-12-17_100001.jpg'], [datetime.datetime(2025, 12, 17, 10, 15, 1), 'citra_2025-12-17_101501.jpg'], [datetime.datetime(2025, 12, 17, 10, 30, 1), 'citra_2025-12-17_103001.jpg'], [datetime.datetime(2025, 12, 17, 10, 45, 1), 'citra_2025-12-17_104501.jpg'], [datetime.datetime(2025, 12, 17, 11, 0, 1), 'citra_2025-12-17_110001.jpg'], [datetime.datetime(2025, 12, 17, 11, 15, 1), 'citra_2025-12-17_111501.jpg'], [datetime.datetime(2025, 12, 17, 11, 30, 1), 'citra_2025-12-17_113001.jpg'], [datetime.datetime(2025, 12, 17, 11, 45, 1), 'citra_2025-12-17_114501.jpg'], [datetime.datetime(2025, 12, 17, 12, 0, 1), 'citra_2025-12-17_120001.jpg'], [datetime.datetime(2025, 12, 17, 12, 15, 1), 'citra_2025-12-17_121501.jpg'], [datetime.datetime(2025, 12, 17, 12, 30, 1), 'citra_2025-12-17_123001.jpg'], [datetime.datetime(2025, 12, 17, 12, 45, 1), 'citra_2025-12-17_124501.jpg'], [datetime.datetime(2025, 12, 17, 13, 0, 1), 'citra_2025-12-17_130001.jpg'], [datetime.datetime(2025, 12, 17, 13, 15, 1), 'citra_2025-12-17_131501.jpg'], [datetime.datetime(2025, 12, 17, 13, 30, 1), 'citra_2025-12-17_133001.jpg'], [datetime.datetime(2025, 12, 17, 13, 45, 1), 'citra_2025-12-17_134501.jpg'], [datetime.datetime(2025, 12, 17, 14, 0, 1), 'citra_2025-12-17_140001.jpg'], [datetime.datetime(2025, 12, 17, 14, 15, 1), 'citra_2025-12-17_141501.jpg'], [datetime.datetime(2025, 12, 17, 14, 30, 1), 'citra_2025-12-17_143001.jpg'], [datetime.datetime(2025, 12, 17, 14, 45, 1), 'citra_2025-12-17_144501.jpg'], [datetime.datetime(2025, 12, 17, 15, 0, 1), 'citra_2025-12-17_150001.jpg'], [datetime.datetime(2025, 12, 18, 6, 0, 1), 'citra_2025-12-18_060001.jpg'], [datetime.datetime(2025, 12, 18, 6, 15, 1), 'citra_2025-12-18_061501.jpg'], [datetime.datetime(2025, 12, 18, 6, 30, 1), 'citra_2025-12-18_063001.jpg'], [datetime.datetime(2025, 12, 18, 6, 45, 1), 'citra_2025-12-18_064501.jpg'], [datetime.datetime(2025, 12, 18, 7, 0, 1), 'citra_2025-12-18_070001.jpg'], [datetime.datetime(2025, 12, 18, 7, 15, 1), 'citra_2025-12-18_071501.jpg'], [datetime.datetime(2025, 12, 18, 7, 30, 1), 'citra_2025-12-18_073001.jpg'], [datetime.datetime(2025, 12, 18, 7, 45, 1), 'citra_2025-12-18_074501.jpg'], [datetime.datetime(2025, 12, 18, 8, 0, 1), 'citra_2025-12-18_080001.jpg'], [datetime.datetime(2025, 12, 18, 8, 15, 1), 'citra_2025-12-18_081501.jpg'], [datetime.datetime(2025, 12, 18, 8, 30, 1), 'citra_2025-12-18_083001.jpg'], [datetime.datetime(2025, 12, 18, 8, 45, 1), 'citra_2025-12-18_084501.jpg'], [datetime.datetime(2025, 12, 18, 9, 0, 1), 'citra_2025-12-18_090001.jpg'], [datetime.datetime(2025, 12, 18, 9, 15, 1), 'citra_2025-12-18_091501.jpg'], [datetime.datetime(2025, 12, 18, 9, 30, 1), 'citra_2025-12-18_093001.jpg'], [datetime.datetime(2025, 12, 18, 9, 45, 1), 'citra_2025-12-18_094501.jpg'], [datetime.datetime(2025, 12, 18, 10, 0, 1), 'citra_2025-12-18_100001.jpg'], [datetime.datetime(2025, 12, 18, 10, 15, 1), 'citra_2025-12-18_101501.jpg'], [datetime.datetime(2025, 12, 18, 10, 30, 1), 'citra_2025-12-18_103001.jpg'], [datetime.datetime(2025, 12, 18, 10, 45, 1), 'citra_2025-12-18_104501.jpg'], [datetime.datetime(2025, 12, 18, 11, 0, 1), 'citra_2025-12-18_110001.jpg'], [datetime.datetime(2025, 12, 18, 11, 15, 1), 'citra_2025-12-18_111501.jpg'], [datetime.datetime(2025, 12, 18, 11, 30, 1), 'citra_2025-12-18_113001.jpg'], [datetime.datetime(2025, 12, 18, 11, 45, 1), 'citra_2025-12-18_114501.jpg'], [datetime.datetime(2025, 12, 18, 12, 0, 1), 'citra_2025-12-18_120001.jpg'], [datetime.datetime(2025, 12, 18, 12, 15, 1), 'citra_2025-12-18_121501.jpg'], [datetime.datetime(2025, 12, 18, 12, 30, 1), 'citra_2025-12-18_123001.jpg'], [datetime.datetime(2025, 12, 18, 12, 45, 1), 'citra_2025-12-18_124501.jpg'], [datetime.datetime(2025, 12, 18, 13, 0, 1), 'citra_2025-12-18_130001.jpg'], [datetime.datetime(2025, 12, 18, 13, 15, 1), 'citra_2025-12-18_131501.jpg'], [datetime.datetime(2025, 12, 18, 13, 30, 1), 'citra_2025-12-18_133001.jpg'], [datetime.datetime(2025, 12, 18, 13, 45, 1), 'citra_2025-12-18_134501.jpg'], [datetime.datetime(2025, 12, 18, 14, 0, 1), 'citra_2025-12-18_140001.jpg'], [datetime.datetime(2025, 12, 18, 14, 15, 1), 'citra_2025-12-18_141501.jpg'], [datetime.datetime(2025, 12, 18, 14, 30, 1), 'citra_2025-12-18_143001.jpg'], [datetime.datetime(2025, 12, 18, 14, 45, 1), 'citra_2025-12-18_144501.jpg'], [datetime.datetime(2025, 12, 18, 15, 0, 1), 'citra_2025-12-18_150001.jpg'], [datetime.datetime(2025, 12, 19, 6, 0, 1), 'citra_2025-12-19_060001.jpg'], [datetime.datetime(2025, 12, 19, 6, 15, 1), 'citra_2025-12-19_061501.jpg'], [datetime.datetime(2025, 12, 19, 6, 30, 1), 'citra_2025-12-19_063001.jpg'], [datetime.datetime(2025, 12, 19, 6, 45, 1), 'citra_2025-12-19_064501.jpg'], [datetime.datetime(2025, 12, 19, 7, 0, 1), 'citra_2025-12-19_070001.jpg'], [datetime.datetime(2025, 12, 19, 7, 15, 1), 'citra_2025-12-19_071501.jpg'], [datetime.datetime(2025, 12, 19, 7, 30, 1), 'citra_2025-12-19_073001.jpg'], [datetime.datetime(2025, 12, 19, 7, 45, 1), 'citra_2025-12-19_074501.jpg'], [datetime.datetime(2025, 12, 19, 8, 0, 1), 'citra_2025-12-19_080001.jpg'], [datetime.datetime(2025, 12, 19, 8, 15, 1), 'citra_2025-12-19_081501.jpg'], [datetime.datetime(2025, 12, 19, 8, 30, 1), 'citra_2025-12-19_083001.jpg'], [datetime.datetime(2025, 12, 19, 8, 45, 1), 'citra_2025-12-19_084501.jpg'], [datetime.datetime(2025, 12, 19, 9, 0, 1), 'citra_2025-12-19_090001.jpg'], [datetime.datetime(2025, 12, 19, 9, 15, 1), 'citra_2025-12-19_091501.jpg'], [datetime.datetime(2025, 12, 19, 9, 30, 1), 'citra_2025-12-19_093001.jpg'], [datetime.datetime(2025, 12, 19, 9, 45, 1), 'citra_2025-12-19_094501.jpg'], [datetime.datetime(2025, 12, 19, 10, 0, 1), 'citra_2025-12-19_100001.jpg'], [datetime.datetime(2025, 12, 19, 10, 15, 1), 'citra_2025-12-19_101501.jpg'], [datetime.datetime(2025, 12, 19, 10, 30, 1), 'citra_2025-12-19_103001.jpg'], [datetime.datetime(2025, 12, 19, 10, 45, 1), 'citra_2025-12-19_104501.jpg'], [datetime.datetime(2025, 12, 19, 11, 0, 1), 'citra_2025-12-19_110001.jpg'], [datetime.datetime(2025, 12, 19, 11, 15, 1), 'citra_2025-12-19_111501.jpg'], [datetime.datetime(2025, 12, 19, 11, 30, 1), 'citra_2025-12-19_113001.jpg'], [datetime.datetime(2025, 12, 19, 11, 45, 1), 'citra_2025-12-19_114501.jpg'], [datetime.datetime(2025, 12, 19, 12, 0, 1), 'citra_2025-12-19_120001.jpg'], [datetime.datetime(2025, 12, 19, 12, 15, 1), 'citra_2025-12-19_121501.jpg'], [datetime.datetime(2025, 12, 19, 12, 30, 1), 'citra_2025-12-19_123001.jpg'], [datetime.datetime(2025, 12, 19, 12, 45, 1), 'citra_2025-12-19_124501.jpg'], [datetime.datetime(2025, 12, 19, 13, 0, 1), 'citra_2025-12-19_130001.jpg'], [datetime.datetime(2025, 12, 19, 13, 15, 1), 'citra_2025-12-19_131501.jpg'], [datetime.datetime(2025, 12, 19, 13, 30, 1), 'citra_2025-12-19_133001.jpg'], [datetime.datetime(2025, 12, 19, 13, 45, 1), 'citra_2025-12-19_134501.jpg'], [datetime.datetime(2025, 12, 19, 14, 0, 1), 'citra_2025-12-19_140001.jpg'], [datetime.datetime(2025, 12, 19, 14, 15, 1), 'citra_2025-12-19_141501.jpg'], [datetime.datetime(2025, 12, 19, 14, 30, 1), 'citra_2025-12-19_143001.jpg'], [datetime.datetime(2025, 12, 19, 14, 45, 1), 'citra_2025-12-19_144501.jpg'], [datetime.datetime(2025, 12, 19, 15, 0, 1), 'citra_2025-12-19_150001.jpg'], [datetime.datetime(2025, 12, 19, 15, 15, 1), 'citra_2025-12-19_151501.jpg'], [datetime.datetime(2025, 12, 20, 6, 0, 1), 'citra_2025-12-20_060001.jpg'], [datetime.

In [8]:
import os
import pandas as pd
from datetime import datetime

def map_images_with_tolerance(excel_path, image_folder, output_excel):

    # read excel
    df = pd.read_excel(excel_path)

    # let pandas auto-parse datetime
    df["Date Time"] = pd.to_datetime(df["Date Time"],format="%Y-%m-%d %H:%M:%S")

    df = df.sort_values("Date Time").reset_index(drop=True)


    image_data = []

    # read image timestamps
    for file in os.listdir(image_folder):

        if file.endswith(".jpg"):

            try:
                # citra_2025-12-13_060001.jpg
                name = file.replace("citra_", "").replace(".jpg", "")
                img_time = datetime.strptime(name, "%Y-%m-%d_%H%M%S")

                image_data.append([img_time, file])

            except:
                continue

    img_df = pd.DataFrame(image_data, columns=["img_time", "image_name"])
    img_df = img_df.sort_values("img_time").reset_index(drop=True)

    # IMPORTANT: merge_asof requires sorting
    # img_df = img_df.sort_values("img_time")
    print(img_df)

    # merge with tolerance
    mapped = pd.merge_asof(
        df,
        img_df,
        left_on="Date Time",
        right_on="img_time",
        direction="nearest",
        tolerance=pd.Timedelta("2min")
    )
    # print(mapped)
    return img_df,mapped,df
    # mapped.drop(columns=["img_time"], inplace=True)

    # mapped.to_excel(output_excel, index=False)

    print("Saved:", output_excel)

excel_path = r"Front_down_1_plants_weather_mapped.xlsx"
image_folder = r"F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images"
output_excel = r"Front_images_mapped_images_down_11.xlsx"
a,b,c=map_images_with_tolerance(excel_path, image_folder, output_excel)

               img_time                   image_name
0   2025-12-12 15:00:01  citra_2025-12-12_150001.jpg
1   2025-12-13 06:00:01  citra_2025-12-13_060001.jpg
2   2025-12-13 06:15:01  citra_2025-12-13_061501.jpg
3   2025-12-13 06:30:01  citra_2025-12-13_063001.jpg
4   2025-12-13 06:45:01  citra_2025-12-13_064501.jpg
..                  ...                          ...
316 2025-12-21 10:15:01  citra_2025-12-21_101501.jpg
317 2025-12-21 10:30:01  citra_2025-12-21_103001.jpg
318 2025-12-21 10:45:01  citra_2025-12-21_104501.jpg
319 2025-12-21 11:00:01  citra_2025-12-21_110001.jpg
320 2025-12-21 11:15:01  citra_2025-12-21_111501.jpg

[321 rows x 2 columns]

In [11]:
b.to_excel('mapped_excel_front_down_1.xlsx', index=False)

In [10]:
b

,Station ID,Date Time,Soil Temp (C),Temp @ 60cm (C),Temp @ 2m (C),Temp @ 10m (C),Relative Humidity (%),Dew Point Temp (C),Rainfall Amount (in),Wind Speed (mph),Wind Direction (deg),Solar Radiation (w/m2),img_time,image_name
0,260,2025-12-12 15:15:00,14.84,23.08,22.61,21.34,29.56,3.96,0.0,4.79,236.60,379.7,NaT,NaN
1,260,2025-12-12 15:30:00,15.00,23.10,22.18,21.14,30.02,3.80,0.0,5.77,216.70,340.9,NaT,NaN
2,260,2025-12-12 15:45:00,15.15,22.48,22.34,21.30,29.40,3.65,0.0,4.81,238.00,299.2,NaT,NaN
3,260,2025-12-12 16:00:00,15.28,22.42,22.20,21.47,29.07,3.37,0.0,3.94,253.10,257.0,NaT,NaN
4,260,2025-12-12 16:15:00,15.40,22.29,22.19,21.36,30.09,3.85,0.0,3.90,225.70,213.7,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
844,260,2025-12-21 10:15:00,12.44,14.03,15.15,13.73,86.50,12.91,0.0,1.82,41.25,460.3,2025-12-21 10:15:01,citra_2025-12-21_101501.jpg
845,260,2025-12-21 10:30:00,12.46,16.09,16.92,15.31,68.58,11.11,0.0,3.51,31.14,486.9,2025-12-21 10:30:01,citra_2025-12-21_103001.jpg
846,260,2025-12-21 10:45:00,12.49,17.40,17.72,16.29,65.73,11.23,0.0,4.46,35.11,508.2,2025-12-21 10:45:01,citra_2025-12-21_104501.jpg
847,260,2025-12-21 11:00:00,12.54,18.48,18.97,17.27,62.68,11.70,0.0,3.78,44.05,532.5,2025-12-21 11:00:01,citra_2025-12-21_110001.jpg
848,260,2025-12-21 11:15:00,12.61,19.00,19.24,17.75,62.26,11.85,0.0,4.47,61.62,550.0,2025-12-21 11:15:01,citra_2025-12-21_111501.jpg

In [12]:
import pandas as pd
import numpy as np

excel_path = r"F:\strwaberry images\Front_images_mapped_images_down_1.xlsx"

df = pd.read_excel(excel_path)

# convert datetime
df["Date Time"] = pd.to_datetime(df["Date Time"])

# extract date
df["Date"] = df["Date Time"].dt.date

# temperature column
temp_col = "Temp @ 2m (C)"

# calculate daily Tmin and Tmax
daily_temp = df.groupby("Date")[temp_col].agg(
    Tmin="min",
    Tmax="max"
).reset_index()

# parameters
Tbase = 7
Tmax_limit = 30

# apply rules
daily_temp["Tmax"] = daily_temp["Tmax"].clip(upper=Tmax_limit)
daily_temp["Tmin"] = daily_temp["Tmin"].clip(lower=Tbase)

# calculate GDD
daily_temp["GDD"] = ((daily_temp["Tmax"] + daily_temp["Tmin"]) / 2) - Tbase

# rule: negative GDD = 0
daily_temp["GDD"] = daily_temp["GDD"].clip(lower=0)

# cumulative GDD
daily_temp["Cumulative_GDD"] = daily_temp["GDD"].cumsum()

print(daily_temp.head())

# save
daily_temp.to_excel(r"F:\Front_down1_strawberry_gdd.xlsx", index=False)

         Date  Tmin   Tmax    GDD  Cumulative_GDD
0  2025-12-12  7.00  22.61  7.805           7.805
1  2025-12-13  7.00  25.09  9.045          16.850
2  2025-12-14  7.26  24.89  9.075          25.925
3  2025-12-15  7.00  13.32  3.160          29.085
4  2025-12-16  7.00  20.02  6.510          35.595

In [13]:
file = r"Front_images_mapped_images_down_1.xlsx"
df = pd.read_excel(file)

# convert datetime
df["Date Time"] = pd.to_datetime(df["Date Time"])

# extract date
df["date"] = df["Date Time"].dt.date

temp_col = "Temp @ 2m (C)"

# calculate daily Tmax and Tmin
daily = df.groupby("date")[temp_col].agg(["max","min"]).reset_index()
daily.columns = ["date","Tmax","Tmin"]

# GDD parameters
Tbase = 7
Tmax_cap = 30

# apply rules
daily["Tmax"] = daily["Tmax"].clip(upper=Tmax_cap)
daily["Tmin"] = daily["Tmin"].clip(lower=Tbase)

daily["GDD"] = ((daily["Tmax"] + daily["Tmin"]) / 2) - Tbase
daily["GDD"] = daily["GDD"].clip(lower=0)

# merge back into main dataset
df_final = df.merge(daily, on="date", how="left")
df_final

,Station ID,Date Time,Soil Temp (C),Temp @ 60cm (C),Temp @ 2m (C),Temp @ 10m (C),Relative Humidity (%),Dew Point Temp (C),Rainfall Amount (in),Wind Speed (mph),Wind Direction (deg),Solar Radiation (w/m2),image_name,date,Tmax,Tmin,GDD
0,260,2025-12-12 15:15:00,14.84,23.08,22.61,21.34,29.56,3.96,0.0,4.79,236.60,379.7,NaN,2025-12-12,22.61,7.0,7.805
1,260,2025-12-12 15:30:00,15.00,23.10,22.18,21.14,30.02,3.80,0.0,5.77,216.70,340.9,NaN,2025-12-12,22.61,7.0,7.805
2,260,2025-12-12 15:45:00,15.15,22.48,22.34,21.30,29.40,3.65,0.0,4.81,238.00,299.2,NaN,2025-12-12,22.61,7.0,7.805
3,260,2025-12-12 16:00:00,15.28,22.42,22.20,21.47,29.07,3.37,0.0,3.94,253.10,257.0,NaN,2025-12-12,22.61,7.0,7.805
4,260,2025-12-12 16:15:00,15.40,22.29,22.19,21.36,30.09,3.85,0.0,3.90,225.70,213.7,NaN,2025-12-12,22.61,7.0,7.805
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
844,260,2025-12-21 10:15:00,12.44,14.03,15.15,13.73,86.50,12.91,0.0,1.82,41.25,460.3,citra_2025-12-21_101501.jpg,2025-12-21,19.24,7.0,6.120
845,260,2025-12-21 10:30:00,12.46,16.09,16.92,15.31,68.58,11.11,0.0,3.51,31.14,486.9,citra_2025-12-21_103001.jpg,2025-12-21,19.24,7.0,6.120
846,260,2025-12-21 10:45:00,12.49,17.40,17.72,16.29,65.73,11.23,0.0,4.46,35.11,508.2,citra_2025-12-21_104501.jpg,2025-12-21,19.24,7.0,6.120
847,260,2025-12-21 11:00:00,12.54,18.48,18.97,17.27,62.68,11.70,0.0,3.78,44.05,532.5,citra_2025-12-21_110001.jpg,2025-12-21,19.24,7.0,6.120
848,260,2025-12-21 11:15:00,12.61,19.00,19.24,17.75,62.26,11.85,0.0,4.47,61.62,550.0,citra_2025-12-21_111501.jpg,2025-12-21,19.24,7.0,6.120

In [16]:
import cv2
import numpy as np
import pandas as pd
from pathlib import Path

# load your main dataset
# df_final = pd.read_excel(r"F:\dataset_with_gdd.xlsx")

folder = r"F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images"

green_dict = {}

for path in Path(folder).glob("*.jpg"):

    img = cv2.imread(str(path))
    if img is None:
        continue

    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

    lower_green = np.array([35,40,40])
    upper_green = np.array([90,255,255])

    mask = cv2.inRange(hsv, lower_green, upper_green)

    kernel = np.ones((5,5),np.uint8)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)

    green_pixels = cv2.countNonZero(mask)

    green_dict[path.name] = green_pixels


# add green_pixels column using image_name
df_final["green_pixels"] = df_final["image_name"].map(green_dict)
df_final

,Station ID,Date Time,Soil Temp (C),Temp @ 60cm (C),Temp @ 2m (C),Temp @ 10m (C),Relative Humidity (%),Dew Point Temp (C),Rainfall Amount (in),Wind Speed (mph),Wind Direction (deg),Solar Radiation (w/m2),image_name,date,Tmax,Tmin,GDD,green_pixels
0,260,2025-12-12 15:15:00,14.84,23.08,22.61,21.34,29.56,3.96,0.0,4.79,236.60,379.7,NaN,2025-12-12,22.61,7.0,7.805,NaN
1,260,2025-12-12 15:30:00,15.00,23.10,22.18,21.14,30.02,3.80,0.0,5.77,216.70,340.9,NaN,2025-12-12,22.61,7.0,7.805,NaN
2,260,2025-12-12 15:45:00,15.15,22.48,22.34,21.30,29.40,3.65,0.0,4.81,238.00,299.2,NaN,2025-12-12,22.61,7.0,7.805,NaN
3,260,2025-12-12 16:00:00,15.28,22.42,22.20,21.47,29.07,3.37,0.0,3.94,253.10,257.0,NaN,2025-12-12,22.61,7.0,7.805,NaN
4,260,2025-12-12 16:15:00,15.40,22.29,22.19,21.36,30.09,3.85,0.0,3.90,225.70,213.7,NaN,2025-12-12,22.61,7.0,7.805,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
844,260,2025-12-21 10:15:00,12.44,14.03,15.15,13.73,86.50,12.91,0.0,1.82,41.25,460.3,citra_2025-12-21_101501.jpg,2025-12-21,19.24,7.0,6.120,132909.0
845,260,2025-12-21 10:30:00,12.46,16.09,16.92,15.31,68.58,11.11,0.0,3.51,31.14,486.9,citra_2025-12-21_103001.jpg,2025-12-21,19.24,7.0,6.120,145134.0
846,260,2025-12-21 10:45:00,12.49,17.40,17.72,16.29,65.73,11.23,0.0,4.46,35.11,508.2,citra_2025-12-21_104501.jpg,2025-12-21,19.24,7.0,6.120,138203.0
847,260,2025-12-21 11:00:00,12.54,18.48,18.97,17.27,62.68,11.70,0.0,3.78,44.05,532.5,citra_2025-12-21_110001.jpg,2025-12-21,19.24,7.0,6.120,129498.0
848,260,2025-12-21 11:15:00,12.61,19.00,19.24,17.75,62.26,11.85,0.0,4.47,61.62,550.0,citra_2025-12-21_111501.jpg,2025-12-21,19.24,7.0,6.120,129665.0

In [18]:
from plotly import express as px
df=df_final
df["Date Time"] = pd.to_datetime(df["Date Time"])
df["date"] = df["Date Time"].dt.date

# df = df.dropna(subset=["green_pixels"])
daily = df_final.groupby("date").agg({
    "green_pixels":"mean",
    "GDD":"first"
}).reset_index()

# plot
fig = px.scatter(
    daily,
    x="date",
    y="green_pixels",
    color="GDD",
    title="Front row donwn 1 plant Strawberry Growth Over Time (Green Pixels) with GDD",
    labels={
        "date":"Date",
        "green_pixels":"Average Green Pixel Area",
        "GDD":"Daily GDD"
    }
)

fig.update_traces(marker=dict(size=9))

fig.show()

In [19]:
df.to_excel('Front_Images_mapped_down1_gdd.xlsx')

In [22]:
daily = df.groupby("date").agg({
    "Solar Radiation (w/m2)": "sum",
    "green_pixels": "sum"
}).reset_index()

In [23]:
import plotly.express as px

fig = px.scatter(
    daily,
    x="Solar Radiation (w/m2)",
    y="green_pixels",
    trendline="ols",
    title="Daily Solar Radiation vs Plant Size"
)

fig.show()

In [2]:
from ultralytics import YOLO
import pandas as pd
import os

# Load model
model = YOLO("best.pt")

image_folder = r"F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images"
results_list = []
failed_images = []

for img in os.listdir(image_folder):

    img_path = os.path.join(image_folder, img)

    try:
        # Run inference
        results = model(img_path)

        class_counts = {}
        total = 0

        for r in results:
            if r.boxes is None:
                continue

            boxes = r.boxes.cls.tolist()

            for cls in boxes:
                class_name = model.names[int(cls)]

                class_counts[class_name] = class_counts.get(class_name, 0) + 1
                total += 1

        row = {
            "image_name": img,
            "total_objects": total
        }

        row.update(class_counts)
        results_list.append(row)

    except Exception as e:
        print(f"Error processing {img}: {e}")
        failed_images.append(img)
        continue

# Convert to dataframe
df = pd.DataFrame(results_list).fillna(0)

# Save detection results
df.to_excel("yolo_results_front.xlsx", index=False)

# Save failed images list
if failed_images:
    failed_df = pd.DataFrame({"failed_images": failed_images})
    failed_df.to_excel("failed_images_front.xlsx", index=False)

print("Processing complete.")
print(f"Successful images: {len(results_list)}")
print(f"Failed images: {len(failed_images)}")

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-12_150001.jpg: 480x640 2 Gs, 1 W, 1 P, 2 Rs, 532.9ms
Speed: 4.0ms preprocess, 532.9ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_060001.jpg: 480x640 1 R, 458.1ms
Speed: 4.1ms preprocess, 458.1ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_061501.jpg: 480x640 2 Rs, 508.2ms
Speed: 3.9ms preprocess, 508.2ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_063001.jpg: 480x640 1 P, 1 R, 514.7ms
Speed: 3.6ms preprocess, 514.7ms inference, 2.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_064501.jpg: 480x640 1 P, 1 R, 514.4ms
Speed: 4.9ms preprocess, 514.4ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_070001.jpg: 480x640 2 Rs, 470.3ms
Speed: 3.5ms preprocess, 470.3ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_071501.jpg: 480x640 1 R, 435.0ms
Speed: 3.2ms preprocess, 435.0ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_073001.jpg: 480x640 (no detections), 302.1ms
Speed: 2.9ms preprocess, 302.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_074501.jpg: 480x640 (no detections), 300.6ms
Speed: 2.4ms preprocess, 300.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_080001.jpg: 480x640 (no detections), 358.0ms
Speed: 2.4ms preprocess, 358.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_081501.jpg: 480x640 (no detections), 300.1ms
Speed: 3.1ms preprocess, 300.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_083001.jpg: 480x640 3 Ws, 295.6ms
Speed: 2.3ms preprocess, 295.6ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_084501.jpg: 480x640 2 Ws, 296.1ms
Speed: 2.3ms preprocess, 296.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_090001.jpg: 480x640 1 R, 291.5ms
Speed: 2.7ms preprocess, 291.5ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_091501.jpg: 480x640 1 G, 2 Rs, 286.3ms
Speed: 2.5ms preprocess, 286.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_093001.jpg: 480x640 2 Rs, 273.7ms
Speed: 1.8ms preprocess, 273.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_094501.jpg: 480x640 4 Rs, 275.9ms
Speed: 2.0ms preprocess, 275.9ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_100001.jpg: 480x640 3 Rs, 276.2ms
Speed: 2.2ms preprocess, 276.2ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_101501.jpg: 480x640 3 Rs, 322.0ms
Speed: 1.7ms preprocess, 322.0ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_103001.jpg: 480x640 3 Rs, 269.2ms
Speed: 2.2ms preprocess, 269.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_104501.jpg: 480x640 1 G, 4 Rs, 294.7ms
Speed: 1.7ms preprocess, 294.7ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_110001.jpg: 480x640 1 G, 3 Rs, 433.3ms
Speed: 2.1ms preprocess, 433.3ms inference, 4.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_111501.jpg: 480x640 2 Gs, 3 Rs, 466.3ms
Speed: 3.9ms preprocess, 466.3ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_113001.jpg: 480x640 4 Rs, 477.8ms
Speed: 3.1ms preprocess, 477.8ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_114501.jpg: 480x640 3 Gs, 1 W, 3 Rs, 487.0ms
Speed: 10.3ms preprocess, 487.0ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_120001.jpg: 480x640 1 G, 2 Rs, 449.1ms
Speed: 3.1ms preprocess, 449.1ms inference, 1.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_121501.jpg: 480x640 1 G, 3 Rs, 472.3ms
Speed: 2.6ms preprocess, 472.3ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_123001.jpg: 480x640 2 Rs, 485.9ms
Speed: 3.2ms preprocess, 485.9ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_124501.jpg: 480x640 1 G, 2 Rs, 481.1ms
Speed: 3.3ms preprocess, 481.1ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_130001.jpg: 480x640 2 Rs, 545.9ms
Speed: 3.1ms preprocess, 545.9ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_131501.jpg: 480x640 2 Rs, 532.4ms
Speed: 3.5ms preprocess, 532.4ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_133001.jpg: 480x640 1 G, 2 Ws, 2 Rs, 509.6ms
Speed: 3.4ms preprocess, 509.6ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_134501.jpg: 480x640 1 G, 2 Rs, 513.1ms
Speed: 4.6ms preprocess, 513.1ms inference, 1.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_140001.jpg: 480x640 2 Gs, 3 Rs, 489.0ms
Speed: 3.8ms preprocess, 489.0ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_141501.jpg: 480x640 1 G, 1 W, 1 R, 501.5ms
Speed: 3.1ms preprocess, 501.5ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_143001.jpg: 480x640 1 G, 1 W, 1 R, 528.6ms
Speed: 2.9ms preprocess, 528.6ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_144501.jpg: 480x640 1 G, 1 W, 2 Rs, 533.9ms
Speed: 3.4ms preprocess, 533.9ms inference, 2.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-13_150001.jpg: 480x640 1 G, 1 W, 2 Rs, 501.7ms
Speed: 3.6ms preprocess, 501.7ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_060001.jpg: 480x640 2 Rs, 501.3ms
Speed: 5.9ms preprocess, 501.3ms inference, 1.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_061501.jpg: 480x640 1 R, 481.2ms
Speed: 5.4ms preprocess, 481.2ms inference, 3.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_063001.jpg: 480x640 1 G, 1 R, 540.2ms
Speed: 4.3ms preprocess, 540.2ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_064501.jpg: 480x640 (no detections), 522.3ms
Speed: 4.3ms preprocess, 522.3ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_070001.jpg: 480x640 1 G, 1 R, 507.5ms
Speed: 4.0ms preprocess, 507.5ms inference, 3.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_071501.jpg: 480x640 1 R, 587.5ms
Speed: 3.8ms preprocess, 587.5ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_073001.jpg: 480x640 (no detections), 508.5ms
Speed: 4.6ms preprocess, 508.5ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_074501.jpg: 480x640 (no detections), 483.1ms
Speed: 4.4ms preprocess, 483.1ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_080001.jpg: 480x640 (no detections), 524.8ms
Speed: 4.8ms preprocess, 524.8ms inference, 1.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_081501.jpg: 480x640 1 G, 502.5ms
Speed: 4.2ms preprocess, 502.5ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_083001.jpg: 480x640 (no detections), 503.0ms
Speed: 3.7ms preprocess, 503.0ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_084501.jpg: 480x640 (no detections), 485.7ms
Speed: 3.7ms preprocess, 485.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_090001.jpg: 480x640 1 G, 2 Rs, 488.1ms
Speed: 3.3ms preprocess, 488.1ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_091501.jpg: 480x640 2 Rs, 520.9ms
Speed: 4.2ms preprocess, 520.9ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_093001.jpg: 480x640 2 Rs, 515.4ms
Speed: 4.4ms preprocess, 515.4ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_094501.jpg: 480x640 2 Gs, 4 Rs, 507.8ms
Speed: 7.7ms preprocess, 507.8ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_100001.jpg: 480x640 1 G, 3 Rs, 484.6ms
Speed: 7.9ms preprocess, 484.6ms inference, 2.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_101501.jpg: 480x640 1 G, 3 Rs, 496.2ms
Speed: 5.0ms preprocess, 496.2ms inference, 3.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_103001.jpg: 480x640 3 Rs, 494.0ms
Speed: 6.4ms preprocess, 494.0ms inference, 1.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_104501.jpg: 480x640 2 Rs, 538.4ms
Speed: 5.6ms preprocess, 538.4ms inference, 2.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_110001.jpg: 480x640 1 G, 4 Rs, 566.6ms
Speed: 5.7ms preprocess, 566.6ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_111501.jpg: 480x640 5 Rs, 455.7ms
Speed: 4.4ms preprocess, 455.7ms inference, 3.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_113001.jpg: 480x640 2 Gs, 3 Rs, 470.2ms
Speed: 4.5ms preprocess, 470.2ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_114501.jpg: 480x640 1 G, 4 Rs, 468.5ms
Speed: 2.7ms preprocess, 468.5ms inference, 2.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_120001.jpg: 480x640 1 G, 3 Rs, 455.1ms
Speed: 3.4ms preprocess, 455.1ms inference, 1.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_121501.jpg: 480x640 3 Rs, 441.7ms
Speed: 3.5ms preprocess, 441.7ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_123001.jpg: 480x640 1 G, 1 W, 2 Rs, 430.9ms
Speed: 3.7ms preprocess, 430.9ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_124501.jpg: 480x640 1 W, 2 Rs, 456.1ms
Speed: 2.9ms preprocess, 456.1ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_130001.jpg: 480x640 2 Rs, 441.8ms
Speed: 4.3ms preprocess, 441.8ms inference, 1.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_131501.jpg: 480x640 3 Rs, 494.1ms
Speed: 4.2ms preprocess, 494.1ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_133001.jpg: 480x640 1 G, 2 Rs, 457.6ms
Speed: 4.1ms preprocess, 457.6ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_134501.jpg: 480x640 1 G, 2 Rs, 453.2ms
Speed: 4.9ms preprocess, 453.2ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_140001.jpg: 480x640 1 W, 3 Rs, 429.5ms
Speed: 3.7ms preprocess, 429.5ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_141501.jpg: 480x640 3 Rs, 419.2ms
Speed: 3.0ms preprocess, 419.2ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_143001.jpg: 480x640 1 G, 1 W, 2 Rs, 402.7ms
Speed: 2.7ms preprocess, 402.7ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_144501.jpg: 480x640 1 G, 3 Ws, 2 Rs, 516.3ms
Speed: 2.6ms preprocess, 516.3ms inference, 1.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-14_150001.jpg: 480x640 1 G, 1 R, 409.5ms
Speed: 2.6ms preprocess, 409.5ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-15_060001.jpg: 480x640 2 Rs, 426.3ms
Speed: 3.0ms preprocess, 426.3ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-15_061501.jpg: 480x640 3 Rs, 415.9ms
Speed: 3.3ms preprocess, 415.9ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-15_063001.jpg: 480x640 2 Rs, 394.0ms
Speed: 2.5ms preprocess, 394.0ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_1\preprocessed_images\citra_2025-12-15_064501.jpg: 480x640 (no detections), 417.3ms
Speed: 2.8ms preprocess, 417.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)
