In [3]:
import os
from datetime import datetime

def get_min_max_timestamp(folder_path):
    timestamps = []

    for file in os.listdir(folder_path):
        if file.endswith(".jpg"):
            try:
                # remove prefix and extension
                name = file.replace("citra_", "").replace(".jpg", "")
                
                # convert to datetime
                dt = datetime.strptime(name, "%Y-%m-%d_%H%M%S")
                timestamps.append(dt)

            except Exception as e:
                print(f"Skipping file {file}: {e}")

    if not timestamps:
        return None, None

    return min(timestamps), max(timestamps)


folder = r"F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images"

min_time, max_time = get_min_max_timestamp(folder)

print("Earliest Timestamp:", min_time)
print("Latest Timestamp:", max_time)

Earliest Timestamp: 2025-12-12 16:30:01
Latest Timestamp: 2026-01-18 18:45:01

In [4]:
import os
import pandas as pd
from datetime import datetime

def create_timestamp_excel(folder_path, output_excel):
    records = []

    for file in os.listdir(folder_path):
        if file.endswith(".jpg"):
            try:
                name = file.replace(".jpg", "")
                dt = datetime.strptime(name, "%Y-%m-%d_%H-%M")

                records.append({
                    "filename": file,
                    "date": dt.date(),
                    "time": dt.time(),
                    "timestamp": dt
                })

            except Exception as e:
                print(f"Skipping {file}: {e}")

    df = pd.DataFrame(records)

    # sort by time
    df = df.sort_values("timestamp")

    # save excel
    df.to_excel(output_excel, index=False)

    print("Excel saved to:", output_excel)


folder = r"F:\strwaberry images\Front_row_with_text\Cropped_Images_down\down_2\preprocessed_images"
output = r"F:\timestamps.xlsx"

create_timestamp_excel(folder, output)

Excel saved to: F:\timestamps.xlsx

In [2]:
import pandas as pd

def filter_datetime_excel(input_excel, output_excel, start_time, end_time):

    # read excel
    df = pd.read_excel(input_excel)

    # convert Datetime column to datetime format
    df["Date Time"] = pd.to_datetime(df["Date Time"], format="%d-%m-%Y %H:%M")

    # define time range
    start = pd.to_datetime(start_time)
    end = pd.to_datetime(end_time)

    # filter rows
    filtered_df = df[(df["Date Time"] >= start) & (df["Date Time"] <= end)]

    # save new excel
    filtered_df.to_excel(output_excel, index=False)

    print("Filtered Excel saved at:", output_excel)


input_excel = r"FAWN_2025.xlsx"
output_excel = r"down_plants_weather_mapped.xlsx"

start_time = "2025-12-12 16:30:01"
end_time = "2026-01-18 18:45:01"

filter_datetime_excel(input_excel, output_excel, start_time, end_time)

Filtered Excel saved at: down_plants_weather_mapped.xlsx

In [1]:
import pandas as pd

def filter_datetime_excel(input_excel, output_excel, start_time, end_time):

    # read excel
    df = pd.read_excel(input_excel)

    # convert Datetime column to datetime format
    df["Date Time"] = pd.to_datetime(df["Date Time"], format="%d-%m-%Y %H:%M")

    # define time range
    start = pd.to_datetime(start_time)
    end = pd.to_datetime(end_time)

    # filter rows
    filtered_df = df[(df["Date Time"] >= start) & (df["Date Time"] <= end)]

    # save new excel
    filtered_df.to_excel(output_excel, index=False)

    print("Filtered Excel saved at:", output_excel)


input_excel = r"FAWN_2026.xlsx"
output_excel = r"down_plants_weather_mapped_2026.xlsx"

start_time = "2025-12-12 16:30:01"
end_time = "2026-01-18 18:45:01"

filter_datetime_excel(input_excel, output_excel, start_time, end_time)

Filtered Excel saved at: down_plants_weather_mapped_2026.xlsx

In [ ]:
import os
import pandas as pd
from datetime import datetime

def map_images_to_excel(excel_path, image_folder, output_excel):

    # read excel
    df = pd.read_excel(excel_path)
    df["Date Time"] = pd.to_datetime(df["Date Time"], format="%d-%m-%Y %H:%M")

    image_data = []

    # read image timestamps
    for file in os.listdir(image_folder):
        if file.endswith(".jpg"):

            try:
                name = file.replace("citra_", "").replace(".jpg", "")
                img_time = datetime.strptime(name, "%Y-%m-%d_%H%M%S")

                image_data.append((img_time, file))

            except:
                try:
                    name = file.replace(".jpg", "")
                    img_time = datetime.strptime(name, "%Y-%m-%d_%H-%M")

                    image_data.append((img_time, file))
                except:
                    continue

    # convert to dataframe
    img_df = pd.DataFrame(image_data, columns=["img_time", "image_name"])
    img_df = img_df.sort_values("img_time")

    # map nearest timestamp
    df["image_name"] = df["Date Time"].apply(
        lambda x: img_df.iloc[(img_df["img_time"] - x).abs().argsort()[:1]]["image_name"].values[0]
    )

    # save new excel
    df.to_excel(output_excel, index=False)

    print("Mapped Excel saved:", output_excel)


excel_path = r"down_plants_weather_mapped.xlsx"
image_folder = r"back row upated with text\Cropped_Images\down_2\preprocessed_images"
output_excel = r"images_mapped_images_down.xlsx"

map_images_to_excel(excel_path, image_folder, output_excel)

Mapped Excel saved: images_mapped_images_down.xlsx

In [8]:
import os
import pandas as pd
from datetime import datetime

def map_images_with_tolerance(excel_path, image_folder, output_excel):

    # read excel
    df = pd.read_excel(excel_path)
    df["Date Time"] = pd.to_datetime(df["Date Time"], format="%d-%m-%Y %H:%M")
    df = df.sort_values("Date Time")

    image_data = []

    # read image timestamps
    for file in os.listdir(image_folder):

        if file.endswith(".jpg"):
            try:
                name = file.replace("citra_", "").replace(".jpg", "")
                img_time = datetime.strptime(name, "%Y-%m-%d_%H%M%S")
            except:
                try:
                    name = file.replace(".jpg", "")
                    img_time = datetime.strptime(name, "%Y-%m-%d_%H-%M")
                except:
                    continue

            image_data.append([img_time, file])

    img_df = pd.DataFrame(image_data, columns=["img_time", "image_name"])
    img_df = img_df.sort_values("img_time")

    # nearest merge with tolerance ±5 minutes
    mapped = pd.merge_asof(
        df,
        img_df,
        left_on="Date Time",
        right_on="img_time",
        direction="nearest",
        tolerance=pd.Timedelta("5min")
    )

    mapped.drop(columns=["img_time"], inplace=True)

    mapped.to_excel(output_excel, index=False)

    print("Saved:", output_excel)

excel_path = r"down_plants_weather_mapped.xlsx"
image_folder = r"back row upated with text\Cropped_Images\down_2\preprocessed_images"
output_excel = r"images_mapped_images_down.xlsx"

map_images_with_tolerance(excel_path, image_folder, output_excel)

Saved: images_mapped_images_down.xlsx

In [11]:
import pandas as pd

excel_path = r"images_mapped_images_down.xlsx"

df = pd.read_excel(excel_path)

# count mapped images
mapped_count = df["Image_name"].notna().sum()

print("Total mapped images:", mapped_count)

Total mapped images: 1557

In [16]:
df=pd.read_excel("images_mapped_down2.xlsx")

df_filter=df_filtered = df[df["Image_name"].notna()]
# if image name is none  than remove that row.

In [17]:
df_filter

,Station ID,Date Time,Soil Temp (C),Temp @ 60cm (C),Temp @ 2m (C),Temp @ 10m (C),Relative Humidity (%),Dew Point Temp (C),Rainfall Amount (in),Wind Speed (mph),Wind Direction (deg),Solar Radiation (w/m2),Image_name
0,260,2025-12-12 16:45:00,15.60,21.55,21.69,21.16,30.44,3.58,0.00,3.45,229.50,128.50,citra_2025-12-12_164501.jpg
1,260,2025-12-12 17:00:00,15.67,21.67,20.78,21.03,39.15,6.39,0.00,2.14,230.40,89.40,citra_2025-12-12_170001.jpg
2,260,2025-12-12 17:15:00,15.74,19.34,18.13,21.10,48.86,7.21,0.00,0.61,206.10,49.28,citra_2025-12-12_171501.jpg
55,260,2025-12-13 06:30:00,12.38,2.09,3.40,3.28,94.00,2.53,0.00,0.98,87.50,0.01,citra_2025-12-13_063001.jpg
56,260,2025-12-13 06:45:00,12.33,2.02,3.36,3.34,94.00,2.49,0.00,1.22,100.10,0.02,citra_2025-12-13_064501.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3535,260,2026-01-18 12:45:00,12.78,7.24,7.68,6.89,93.40,6.68,0.01,4.33,55.11,121.40,citra_2026-01-18_124501.jpg
3536,260,2026-01-18 13:00:00,12.72,7.32,7.78,7.00,93.40,6.78,0.01,3.28,17.15,111.40,citra_2026-01-18_130001.jpg
3537,260,2026-01-18 13:15:00,12.66,7.18,7.73,6.94,93.50,6.75,0.00,4.12,36.03,76.42,citra_2026-01-18_131501.jpg
3558,260,2026-01-18 18:30:00,12.30,5.11,5.91,5.37,87.50,4.00,0.00,3.61,313.00,0.08,citra_2026-01-18_183001.jpg
3559,260,2026-01-18 18:45:00,12.26,4.71,5.32,5.17,88.30,3.54,0.00,4.09,293.90,0.01,citra_2026-01-18_184501.jpg

In [ ]:
import pandas as pd
import numpy as np

excel_path = r"F:\only_mapped_images.xlsx"

df = pd.read_excel(excel_path)

# convert datetime
df["Date Time"] = pd.to_datetime(df["Date Time"])

# extract date
df["Date"] = df["Date Time"].dt.date

# temperature column
temp_col = "Temp @ 2m (C)"

# calculate daily Tmin and Tmax
daily_temp = df.groupby("Date")[temp_col].agg(
    Tmin="min",
    Tmax="max"
).reset_index()

# parameters
Tbase = 7
Tmax_limit = 30

# apply rules
daily_temp["Tmax"] = daily_temp["Tmax"].clip(upper=Tmax_limit)
daily_temp["Tmin"] = daily_temp["Tmin"].clip(lower=Tbase)

# calculate GDD
daily_temp["GDD"] = ((daily_temp["Tmax"] + daily_temp["Tmin"]) / 2) - Tbase

# rule: negative GDD = 0
daily_temp["GDD"] = daily_temp["GDD"].clip(lower=0)

# cumulative GDD
daily_temp["Cumulative_GDD"] = daily_temp["GDD"].cumsum()

print(daily_temp.head())

# save
daily_temp.to_excel(r"F:\strawberry_gdd.xlsx", index=False)

In [18]:
file = r"images_mapped_down2.xlsx"

df = pd.read_excel(file)

# convert datetime
df["Date Time"] = pd.to_datetime(df["Date Time"])

# extract date
df["date"] = df["Date Time"].dt.date

# use 2m temperature
temp_col = "Temp @ 2m (C)"

# calculate daily max and min
daily_temp = df.groupby("date")[temp_col].agg(["max","min"]).reset_index()
daily_temp.columns = ["date","Tmax","Tmin"]

Tbase = 7
Tmax_cap = 30

# apply rules
daily_temp["Tmax"] = daily_temp["Tmax"].clip(upper=Tmax_cap)
daily_temp["Tmin"] = daily_temp["Tmin"].clip(lower=Tbase)

# GDD formula
daily_temp["GDD"] = ((daily_temp["Tmax"] + daily_temp["Tmin"]) / 2) - Tbase

# no negative GDD
daily_temp["GDD"] = daily_temp["GDD"].clip(lower=0)

print(daily_temp)

          date   Tmax   Tmin     GDD
0   2025-12-12  21.69   7.00   7.345
1   2025-12-13  25.09   7.00   9.045
2   2025-12-14  24.89   7.26   9.075
3   2025-12-15  13.32   7.00   3.160
4   2025-12-16  20.02   7.00   6.510
5   2025-12-17  24.14   7.86   9.000
6   2025-12-18  25.09  10.79  10.940
7   2025-12-19  23.81   7.00   8.405
8   2025-12-20  22.49   7.00   7.745
9   2025-12-21  24.28   7.00   8.640
10  2025-12-22  22.97   7.00   7.985
11  2025-12-23  26.26   9.19  10.725
12  2025-12-24  27.26   8.68  10.970
13  2025-12-25  26.77  10.93  11.850
14  2025-12-26  26.22  10.61  11.415
15  2025-12-27  25.46  15.98  13.720
16  2025-12-28  25.16  13.69  12.425
17  2025-12-29  24.86  10.16  10.510
18  2025-12-30  12.47   7.00   2.735
19  2025-12-31  13.63   7.00   3.315
20  2026-01-01  19.52   7.00   6.260
21  2026-01-02  21.51   7.00   7.255
22  2026-01-03  25.62  13.82  12.720
23  2026-01-04  15.36  11.90   6.630
24  2026-01-05  21.51  10.91   9.210
25  2026-01-06  25.46   8.65  10.055
26  2026-01-07  26.86  14.44  13.650
27  2026-01-08  25.57  12.84  12.205
28  2026-01-09  29.05  15.76  15.405
29  2026-01-10  27.66  14.40  14.030
30  2026-01-11  19.65   7.00   6.325
31  2026-01-12  16.07   7.00   4.535
32  2026-01-13  18.91   7.00   5.955
33  2026-01-14  15.06   9.94   5.500
34  2026-01-15  12.14   7.00   2.570
35  2026-01-16  14.87   7.00   3.935
36  2026-01-17  22.93   7.00   7.965
37  2026-01-18  14.09   7.00   3.545

In [19]:
file = r"images_mapped_down2.xlsx"
df = pd.read_excel(file)

# convert datetime
df["Date Time"] = pd.to_datetime(df["Date Time"])

# extract date
df["date"] = df["Date Time"].dt.date

temp_col = "Temp @ 2m (C)"

# calculate daily Tmax and Tmin
daily = df.groupby("date")[temp_col].agg(["max","min"]).reset_index()
daily.columns = ["date","Tmax","Tmin"]

# GDD parameters
Tbase = 7
Tmax_cap = 30

# apply rules
daily["Tmax"] = daily["Tmax"].clip(upper=Tmax_cap)
daily["Tmin"] = daily["Tmin"].clip(lower=Tbase)

daily["GDD"] = ((daily["Tmax"] + daily["Tmin"]) / 2) - Tbase
daily["GDD"] = daily["GDD"].clip(lower=0)

# merge back into main dataset
df_final = df.merge(daily, on="date", how="left")
df_final

,Station ID,Date Time,Soil Temp (C),Temp @ 60cm (C),Temp @ 2m (C),Temp @ 10m (C),Relative Humidity (%),Dew Point Temp (C),Rainfall Amount (in),Wind Speed (mph),Wind Direction (deg),Solar Radiation (w/m2),Image_name,date,Tmax,Tmin,GDD
0,260,2025-12-12 16:45:00,15.60,21.55,21.69,21.16,30.44,3.58,0.0,3.45,229.5,128.50,citra_2025-12-12_164501.jpg,2025-12-12,21.69,7.0,7.345
1,260,2025-12-12 17:00:00,15.67,21.67,20.78,21.03,39.15,6.39,0.0,2.14,230.4,89.40,citra_2025-12-12_170001.jpg,2025-12-12,21.69,7.0,7.345
2,260,2025-12-12 17:15:00,15.74,19.34,18.13,21.10,48.86,7.21,0.0,0.61,206.1,49.28,citra_2025-12-12_171501.jpg,2025-12-12,21.69,7.0,7.345
3,260,2025-12-12 17:30:00,15.78,15.69,15.99,18.07,59.45,8.10,0.0,0.99,105.6,10.10,NaN,2025-12-12,21.69,7.0,7.345
4,260,2025-12-12 17:45:00,15.81,12.87,14.28,15.60,64.40,7.66,0.0,1.11,160.9,3.27,NaN,2025-12-12,21.69,7.0,7.345
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3555,260,2026-01-18 17:45:00,12.39,6.08,6.67,6.16,87.40,4.73,0.0,6.97,317.4,7.33,NaN,2026-01-18,14.09,7.0,3.545
3556,260,2026-01-18 18:00:00,12.37,5.71,6.29,5.87,86.20,4.15,0.0,6.90,311.5,4.26,NaN,2026-01-18,14.09,7.0,3.545
3557,260,2026-01-18 18:15:00,12.33,5.29,6.03,5.57,86.10,3.88,0.0,4.86,310.5,1.22,NaN,2026-01-18,14.09,7.0,3.545
3558,260,2026-01-18 18:30:00,12.30,5.11,5.91,5.37,87.50,4.00,0.0,3.61,313.0,0.08,citra_2026-01-18_183001.jpg,2026-01-18,14.09,7.0,3.545
3559,260,2026-01-18 18:45:00,12.26,4.71,5.32,5.17,88.30,3.54,0.0,4.09,293.9,0.01,citra_2026-01-18_184501.jpg,2026-01-18,14.09,7.0,3.545

In [ ]:
import cv2
import numpy as np
import pandas as pd
from pathlib import Path
import plotly.express as px
from datetime import datetime

folder = r"F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images"

records = []

for path in sorted(Path(folder).glob("*.jpg")):

    # ---------- READ IMAGE ----------
    img = cv2.imread(str(path))
    if img is None:
        continue

    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

    # ---------- GREEN MASK ----------
    lower_green = np.array([35, 40, 40])
    upper_green = np.array([90, 255, 255])

    mask = cv2.inRange(hsv, lower_green, upper_green)

    kernel = np.ones((5,5),np.uint8)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)

    green_pixels = cv2.countNonZero(mask)

    # ---------- EXTRACT FULL DATETIME ----------
    # citra_2025-12-19_144501
    name = path.stem.replace("citra_", "")
    dt = datetime.strptime(name, "%Y-%m-%d_%H%M%S")

    records.append([dt, green_pixels])

In [20]:
import cv2
import numpy as np
import pandas as pd
from pathlib import Path

# load your main dataset
# df_final = pd.read_excel(r"F:\dataset_with_gdd.xlsx")

folder = r"F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images"

green_dict = {}

for path in Path(folder).glob("*.jpg"):

    img = cv2.imread(str(path))
    if img is None:
        continue

    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

    lower_green = np.array([35,40,40])
    upper_green = np.array([90,255,255])

    mask = cv2.inRange(hsv, lower_green, upper_green)

    kernel = np.ones((5,5),np.uint8)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)

    green_pixels = cv2.countNonZero(mask)

    green_dict[path.name] = green_pixels


# add green_pixels column using image_name
df_final["green_pixels"] = df_final["Image_name"].map(green_dict)
df_final

,Station ID,Date Time,Soil Temp (C),Temp @ 60cm (C),Temp @ 2m (C),Temp @ 10m (C),Relative Humidity (%),Dew Point Temp (C),Rainfall Amount (in),Wind Speed (mph),Wind Direction (deg),Solar Radiation (w/m2),Image_name,date,Tmax,Tmin,GDD,green_pixels
0,260,2025-12-12 16:45:00,15.60,21.55,21.69,21.16,30.44,3.58,0.0,3.45,229.5,128.50,citra_2025-12-12_164501.jpg,2025-12-12,21.69,7.0,7.345,129763.0
1,260,2025-12-12 17:00:00,15.67,21.67,20.78,21.03,39.15,6.39,0.0,2.14,230.4,89.40,citra_2025-12-12_170001.jpg,2025-12-12,21.69,7.0,7.345,133491.0
2,260,2025-12-12 17:15:00,15.74,19.34,18.13,21.10,48.86,7.21,0.0,0.61,206.1,49.28,citra_2025-12-12_171501.jpg,2025-12-12,21.69,7.0,7.345,131782.0
3,260,2025-12-12 17:30:00,15.78,15.69,15.99,18.07,59.45,8.10,0.0,0.99,105.6,10.10,NaN,2025-12-12,21.69,7.0,7.345,NaN
4,260,2025-12-12 17:45:00,15.81,12.87,14.28,15.60,64.40,7.66,0.0,1.11,160.9,3.27,NaN,2025-12-12,21.69,7.0,7.345,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3555,260,2026-01-18 17:45:00,12.39,6.08,6.67,6.16,87.40,4.73,0.0,6.97,317.4,7.33,NaN,2026-01-18,14.09,7.0,3.545,NaN
3556,260,2026-01-18 18:00:00,12.37,5.71,6.29,5.87,86.20,4.15,0.0,6.90,311.5,4.26,NaN,2026-01-18,14.09,7.0,3.545,NaN
3557,260,2026-01-18 18:15:00,12.33,5.29,6.03,5.57,86.10,3.88,0.0,4.86,310.5,1.22,NaN,2026-01-18,14.09,7.0,3.545,NaN
3558,260,2026-01-18 18:30:00,12.30,5.11,5.91,5.37,87.50,4.00,0.0,3.61,313.0,0.08,citra_2026-01-18_183001.jpg,2026-01-18,14.09,7.0,3.545,153805.0
3559,260,2026-01-18 18:45:00,12.26,4.71,5.32,5.17,88.30,3.54,0.0,4.09,293.9,0.01,citra_2026-01-18_184501.jpg,2026-01-18,14.09,7.0,3.545,155061.0

In [23]:
# remove rows without image / green pixels
df = df.dropna(subset=["green_pixels"])

# scatter plot
fig = px.scatter(
    df,
    x="GDD",
    y="green_pixels",
    trendline="ols",
    title="Daily GDD vs Strawberry Green Pixel Area"
)

fig.show()

In [24]:
df["Date Time"] = pd.to_datetime(df["Date Time"])
df["date"] = df["Date Time"].dt.date

df = df.dropna(subset=["green_pixels"])

# aggregate by day
daily = df.groupby("date").agg({
    "green_pixels":"mean",
    "GDD":"first"
}).reset_index()

fig = px.scatter(
    daily,
    x="GDD",
    y="green_pixels",
    title="Daily GDD vs Average Green Pixel Area",
    labels={
        "GDD":"Daily Growing Degree Days",
        "green_pixels":"Average Green Pixel Area"
    }
)

fig.show()

In [25]:
df["Date Time"] = pd.to_datetime(df["Date Time"])
df["date"] = df["Date Time"].dt.date

df = df.dropna(subset=["green_pixels"])

# aggregate by day
daily = df.groupby("date").agg({
    "green_pixels":"mean",
    "GDD":"first"
}).reset_index()

fig = px.scatter(
    daily,
    x="GDD",
    y="green_pixels",
    title="Daily GDD vs Average Green Pixel Area",
    labels={
        "GDD":"Daily Growing Degree Days",
        "green_pixels":"Average Green Pixel Area"
    }
)
fig.show()

In [26]:
daily = df.groupby("date").agg({
    "green_pixels":"mean",
    "GDD":"first"
}).reset_index()

# plot
fig = px.scatter(
    daily,
    x="date",
    y="green_pixels",
    color="GDD",
    title="Strawberry Growth Over Time (Green Pixels) with GDD",
    labels={
        "date":"Date",
        "green_pixels":"Average Green Pixel Area",
        "GDD":"Daily GDD"
    }
)

fig.update_traces(marker=dict(size=9))

fig.show()

In [ ]:
df_final.to_excel(r"F:\final_dataset_down2_with_gdd_and_green_pixels.xlsx", index=False)

In [3]:
import pandas as pd
df=pd.read_excel('final_dataset_back_down2_with_gdd_and_green_pixels.xlsx')
daily = df.groupby("date").agg({
    "Solar Radiation (w/m2)": "sum",
    "green_pixels": "sum"
}).reset_index()
import plotly.express as px

fig = px.scatter(
    daily,
    x="Solar Radiation (w/m2)",
    y="green_pixels",
    trendline="ols",
    title="Daily Solar Radiation vs Plant Size"
)

fig.show()

In [4]:
import pandas as pd
df=pd.read_excel('final_dataset_back_down2_with_gdd_and_green_pixels.xlsx')
daily = df.groupby("date").agg({
    "Solar Radiation (w/m2)": "mean",
    "green_pixels": "mean"
}).reset_index()
import plotly.express as px

fig = px.scatter(
    daily,
    x="Solar Radiation (w/m2)",
    y="green_pixels",
    trendline="ols",
    title="Daily Solar Radiation vs Plant Size"
)

fig.show()

In [6]:
import pandas as pd
import plotly.graph_objects as go

df = pd.read_excel('final_dataset_back_down2_with_gdd_and_green_pixels.xlsx')

# ensure date column is datetime
df["date"] = pd.to_datetime(df["date"])

daily = df.groupby("date").agg({
    "Solar Radiation (w/m2)": "mean",
    "green_pixels": "mean"
}).reset_index()

fig = go.Figure()

# Plant size line
fig.add_trace(go.Scatter(
    x=daily["date"],
    y=daily["green_pixels"],
    mode='lines+markers',
    name='Plant Size (Green Pixels)'
))

# Radiation line (secondary axis)
fig.add_trace(go.Scatter(
    x=daily["date"],
    y=daily["Solar Radiation (w/m2)"],
    mode='lines+markers',
    name='Daily Radiation',
    yaxis='y2'
))

fig.update_layout(
    title="Daily Radiation and Plant Size Over Time of back setup down 2 plant",
    xaxis_title="Date",
    yaxis=dict(title="Green Pixels"),
    yaxis2=dict(
        title="Daily Radiation (W/m² mean)",
        overlaying='y',
        side='right'
    )
)

fig.show()

In [1]:
!pip install ultralytics

Collecting ultralytics
  Downloading ultralytics-8.4.21-py3-none-any.whl.metadata (39 kB)
Requirement already satisfied: numpy>=1.23.0 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from ultralytics) (2.3.5)
Requirement already satisfied: matplotlib>=3.3.0 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from ultralytics) (3.10.8)
Requirement already satisfied: opencv-python>=4.6.0 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from ultralytics) (4.13.0.92)
Requirement already satisfied: pillow>=7.1.2 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from ultralytics) (12.0.0)
Requirement already satisfied: pyyaml>=5.3.1 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from ultralytics) (6.0.3)
Requirement already satisfied: requests>=2.23.0 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from ultralytics) (2.32.5)
Requirement already satisfied: scipy>=1.4.1 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from ultralytics) (1.16.3)
Collecting torch>=1.8.0 (from ultralytics)
  Downloading torch-2.10.0-cp312-cp312-win_amd64.whl.metadata (31 kB)
Collecting torchvision>=0.9.0 (from ultralytics)
  Downloading torchvision-0.25.0-cp312-cp312-win_amd64.whl.metadata (5.4 kB)
Requirement already satisfied: psutil>=5.8.0 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from ultralytics) (7.0.0)
Collecting polars>=0.20.0 (from ultralytics)
  Downloading polars-1.38.1-py3-none-any.whl.metadata (10 kB)
Collecting ultralytics-thop>=2.0.18 (from ultralytics)
  Downloading ultralytics_thop-2.0.18-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (4.61.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (25.0)
Requirement already satisfied: pyparsing>=3 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (2.9.0.post0)
Collecting polars-runtime-32==1.38.1 (from polars>=0.20.0->ultralytics)
  Downloading polars_runtime_32-1.38.1-cp310-abi3-win_amd64.whl.metadata (1.5 kB)
Requirement already satisfied: six>=1.5 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from requests>=2.23.0->ultralytics) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from requests>=2.23.0->ultralytics) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from requests>=2.23.0->ultralytics) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from requests>=2.23.0->ultralytics) (2026.1.4)
Requirement already satisfied: filelock in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from torch>=1.8.0->ultralytics) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from torch>=1.8.0->ultralytics) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from torch>=1.8.0->ultralytics) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from torch>=1.8.0->ultralytics) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from torch>=1.8.0->ultralytics) (2025.10.0)
Requirement already satisfied: setuptools in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from torch>=1.8.0->ultralytics) (80.9.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from sympy>=1.13.3->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\rohan\anaconda3\envs\aml\lib\site-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.2)
Downloading ultralytics-8.4.21-py3-none-any.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ---------------------------------------- 1.2/1.2 MB 19.8 MB/s  0:00:00
Downloading polars-1.38.1-py3-none-any.whl (810 kB)
   ---------------------------------------- 0.0/810.4 kB ? eta -:--:--
   ---------------------------------------- 810.4/810.4 kB 34.3 MB/s  0:00:00
Downloading polars_runtime_32-1.38.1-cp310-abi3-win_amd64.whl (45.7 MB)
   ---------------------------------------- 0.0/45.7 MB ? eta -:--:--
   ----- ---------------------------------- 6.8/45.7 MB 34.9 MB/s eta 0:00:02
   -------------- ------------------------- 16.0/45.7 MB 40.2 MB/s eta 0:00:01
   --------------------- ------------------ 24.9/45.7 MB 40.4 MB/s eta 0:00:01
   ----------------------------- ---------- 33.6/45.7 MB 40.9 MB/s eta 0:00:01
   ------------------------------------- -- 42.5/45.7 MB 41.5 MB/s eta 0:00:01
   ---------------------------------------- 45.7/45.7 MB 38.2 MB/s  0:00:01
Downloading torch-2.10.0-cp312-cp312-win_amd64.whl (113.8 MB)
   ---------------------------------------- 0.0/113.8 MB ? eta -:--:--
   --- ------------------------------------ 8.7/113.8 MB 44.6 MB/s eta 0:00:03
   ------ --------------------------------- 18.9/113.8 MB 45.8 MB/s eta 0:00:03
   --------- ------------------------------ 28.0/113.8 MB 44.5 MB/s eta 0:00:02
   ------------- -------------------------- 37.2/113.8 MB 44.6 MB/s eta 0:00:02
   ---------------- ----------------------- 45.9/113.8 MB 43.6 MB/s eta 0:00:02
   ------------------- -------------------- 54.5/113.8 MB 43.4 MB/s eta 0:00:02
   ---------------------- ----------------- 63.7/113.8 MB 43.7 MB/s eta 0:00:02
   ------------------------- -------------- 72.6/113.8 MB 43.3 MB/s eta 0:00:01
   ----------------------------- ---------- 82.6/113.8 MB 43.9 MB/s eta 0:00:01
   -------------------------------- ------- 92.3/113.8 MB 44.3 MB/s eta 0:00:01
   ----------------------------------- --- 102.5/113.8 MB 44.5 MB/s eta 0:00:01
   --------------------------------------  112.7/113.8 MB 44.7 MB/s eta 0:00:01
   --------------------------------------  113.5/113.8 MB 44.7 MB/s eta 0:00:01
   ---------------------------------------- 113.8/113.8 MB 40.8 MB/s  0:00:02
Downloading torchvision-0.25.0-cp312-cp312-win_amd64.whl (4.3 MB)
   ---------------------------------------- 0.0/4.3 MB ? eta -:--:--
   ---------------------------------------- 4.3/4.3 MB 43.5 MB/s  0:00:00
Downloading ultralytics_thop-2.0.18-py3-none-any.whl (28 kB)
Installing collected packages: polars-runtime-32, torch, polars, ultralytics-thop, torchvision, ultralytics

   ---------------------------------------- 0/6 [polars-runtime-32]
   ---------------------------------------- 0/6 [polars-runtime-32]
   ---------------------------------------- 0/6 [polars-runtime-32]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------------- -------------------------- 2/6 [polars]
   ------------- -------------------------- 2/6 [polars]
   ------------- -------------------------- 2/6 [polars]
   ------------- -------------------------- 2/6 [polars]
   ------------- -------------------------- 2/6 [polars]
   ------------- -------------------------- 2/6 [polars]
   ------------- -------------------------- 2/6 [polars]
   ------------- -------------------------- 2/6 [polars]
   -------------------------- ------------- 4/6 [torchvision]
   -------------------------- ------------- 4/6 [torchvision]
   -------------------------- ------------- 4/6 [torchvision]
   -------------------------- ------------- 4/6 [torchvision]
   -------------------------- ------------- 4/6 [torchvision]
   -------------------------- ------------- 4/6 [torchvision]
   --------------------------------- ------ 5/6 [ultralytics]
   --------------------------------- ------ 5/6 [ultralytics]
   --------------------------------- ------ 5/6 [ultralytics]
   --------------------------------- ------ 5/6 [ultralytics]
   --------------------------------- ------ 5/6 [ultralytics]
   --------------------------------- ------ 5/6 [ultralytics]
   --------------------------------- ------ 5/6 [ultralytics]
   --------------------------------- ------ 5/6 [ultralytics]
   --------------------------------- ------ 5/6 [ultralytics]
   ---------------------------------------- 6/6 [ultralytics]

Successfully installed polars-1.38.1 polars-runtime-32-1.38.1 torch-2.10.0 torchvision-0.25.0 ultralytics-8.4.21 ultralytics-thop-2.0.18

In [5]:
from ultralytics import YOLO
import pandas as pd
import os

# Load model
model = YOLO("best.pt")

image_folder = r"F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images"
results_list = []
failed_images = []

for img in os.listdir(image_folder):

    img_path = os.path.join(image_folder, img)

    try:
        # Run inference
        results = model(img_path)

        class_counts = {}
        total = 0

        for r in results:
            if r.boxes is None:
                continue

            boxes = r.boxes.cls.tolist()

            for cls in boxes:
                class_name = model.names[int(cls)]

                class_counts[class_name] = class_counts.get(class_name, 0) + 1
                total += 1

        row = {
            "image_name": img,
            "total_objects": total
        }

        row.update(class_counts)
        results_list.append(row)

    except Exception as e:
        print(f"Error processing {img}: {e}")
        failed_images.append(img)
        continue

# Convert to dataframe
df = pd.DataFrame(results_list).fillna(0)

# Save detection results
df.to_excel("yolo_results_back.xlsx", index=False)

# Save failed images list
if failed_images:
    failed_df = pd.DataFrame({"failed_images": failed_images})
    failed_df.to_excel("failed_images_back.xlsx", index=False)

print("Processing complete.")
print(f"Successful images: {len(results_list)}")
print(f"Failed images: {len(failed_images)}")

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-12_163001.jpg: 448x640 (no detections), 474.2ms
Speed: 4.0ms preprocess, 474.2ms inference, 1.0ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-12_164501.jpg: 448x640 1 G, 447.1ms
Speed: 3.0ms preprocess, 447.1ms inference, 1.5ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-12_170001.jpg: 448x640 1 G, 433.3ms
Speed: 3.2ms preprocess, 433.3ms inference, 2.1ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-12_171501.jpg: 448x640 1 P, 431.8ms
Speed: 2.8ms preprocess, 431.8ms inference, 1.6ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_063001.jpg: 448x640 1 R, 462.1ms
Speed: 2.5ms preprocess, 462.1ms inference, 1.2ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_064501.jpg: 448x640 (no detections), 450.2ms
Speed: 5.2ms preprocess, 450.2ms inference, 1.0ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_070001.jpg: 448x640 1 G, 491.1ms
Speed: 3.4ms preprocess, 491.1ms inference, 1.3ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_071501.jpg: 448x640 (no detections), 482.3ms
Speed: 3.2ms preprocess, 482.3ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_073001.jpg: 448x640 (no detections), 589.3ms
Speed: 3.8ms preprocess, 589.3ms inference, 1.1ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_074501.jpg: 448x640 1 FL, 2 Ws, 485.7ms
Speed: 2.9ms preprocess, 485.7ms inference, 1.5ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_080001.jpg: 448x640 1 G, 1 W, 511.5ms
Speed: 3.6ms preprocess, 511.5ms inference, 1.5ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_081501.jpg: 448x640 (no detections), 511.3ms
Speed: 3.2ms preprocess, 511.3ms inference, 1.0ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_083001.jpg: 448x640 1 FL, 472.7ms
Speed: 3.4ms preprocess, 472.7ms inference, 1.4ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_084501.jpg: 448x640 (no detections), 506.1ms
Speed: 3.4ms preprocess, 506.1ms inference, 0.9ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_090001.jpg: 448x640 (no detections), 515.6ms
Speed: 3.6ms preprocess, 515.6ms inference, 0.9ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_091501.jpg: 448x640 1 W, 512.6ms
Speed: 3.7ms preprocess, 512.6ms inference, 1.3ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_093001.jpg: 448x640 (no detections), 499.1ms
Speed: 3.9ms preprocess, 499.1ms inference, 0.8ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_094501.jpg: 448x640 (no detections), 502.1ms
Speed: 3.7ms preprocess, 502.1ms inference, 0.9ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_100001.jpg: 448x640 (no detections), 501.5ms
Speed: 3.4ms preprocess, 501.5ms inference, 0.8ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_101501.jpg: 448x640 (no detections), 492.6ms
Speed: 4.8ms preprocess, 492.6ms inference, 1.1ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_103001.jpg: 448x640 (no detections), 544.8ms
Speed: 4.1ms preprocess, 544.8ms inference, 0.8ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_104501.jpg: 448x640 2 Rs, 509.7ms
Speed: 6.7ms preprocess, 509.7ms inference, 1.6ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_110001.jpg: 448x640 (no detections), 552.4ms
Speed: 3.4ms preprocess, 552.4ms inference, 0.8ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_111501.jpg: 448x640 (no detections), 462.5ms
Speed: 4.2ms preprocess, 462.5ms inference, 1.0ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_113001.jpg: 448x640 1 W, 493.4ms
Speed: 6.6ms preprocess, 493.4ms inference, 2.0ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_114501.jpg: 448x640 (no detections), 484.2ms
Speed: 3.9ms preprocess, 484.2ms inference, 0.9ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_120001.jpg: 448x640 (no detections), 491.1ms
Speed: 4.1ms preprocess, 491.1ms inference, 1.0ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_121501.jpg: 448x640 1 W, 491.3ms
Speed: 4.0ms preprocess, 491.3ms inference, 1.3ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_123001.jpg: 448x640 (no detections), 459.3ms
Speed: 4.2ms preprocess, 459.3ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_124501.jpg: 448x640 (no detections), 452.7ms
Speed: 3.5ms preprocess, 452.7ms inference, 1.2ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_130001.jpg: 448x640 (no detections), 491.3ms
Speed: 6.1ms preprocess, 491.3ms inference, 1.0ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_131501.jpg: 448x640 (no detections), 505.9ms
Speed: 5.1ms preprocess, 505.9ms inference, 0.8ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_133001.jpg: 448x640 (no detections), 515.9ms
Speed: 3.6ms preprocess, 515.9ms inference, 0.8ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_134501.jpg: 448x640 (no detections), 478.2ms
Speed: 3.4ms preprocess, 478.2ms inference, 0.9ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_140001.jpg: 448x640 (no detections), 505.9ms
Speed: 2.6ms preprocess, 505.9ms inference, 0.9ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_141501.jpg: 448x640 (no detections), 518.7ms
Speed: 3.2ms preprocess, 518.7ms inference, 1.1ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_143001.jpg: 448x640 (no detections), 527.0ms
Speed: 3.8ms preprocess, 527.0ms inference, 1.2ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_144501.jpg: 448x640 (no detections), 536.2ms
Speed: 3.6ms preprocess, 536.2ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_150001.jpg: 448x640 (no detections), 428.2ms
Speed: 3.5ms preprocess, 428.2ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_151502.jpg: 448x640 (no detections), 461.3ms
Speed: 4.2ms preprocess, 461.3ms inference, 0.9ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_153001.jpg: 448x640 1 R, 462.6ms
Speed: 3.2ms preprocess, 462.6ms inference, 1.5ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_154501.jpg: 448x640 (no detections), 446.3ms
Speed: 3.9ms preprocess, 446.3ms inference, 0.8ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_160001.jpg: 448x640 1 W, 422.3ms
Speed: 3.6ms preprocess, 422.3ms inference, 1.2ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_161501.jpg: 448x640 2 Ws, 444.0ms
Speed: 2.8ms preprocess, 444.0ms inference, 1.4ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_163001.jpg: 448x640 1 G, 434.0ms
Speed: 3.1ms preprocess, 434.0ms inference, 1.1ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_164501.jpg: 448x640 (no detections), 446.7ms
Speed: 3.6ms preprocess, 446.7ms inference, 1.0ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_170001.jpg: 448x640 (no detections), 441.0ms
Speed: 3.9ms preprocess, 441.0ms inference, 0.8ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_074501.jpg: 448x640 1 W, 456.3ms
Speed: 2.8ms preprocess, 456.3ms inference, 1.4ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_080001.jpg: 448x640 1 W, 455.5ms
Speed: 3.5ms preprocess, 455.5ms inference, 1.2ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_081501.jpg: 448x640 (no detections), 441.1ms
Speed: 4.8ms preprocess, 441.1ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_083001.jpg: 448x640 (no detections), 417.2ms
Speed: 3.1ms preprocess, 417.2ms inference, 0.6ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_084501.jpg: 448x640 1 FL, 1 W, 401.6ms
Speed: 4.1ms preprocess, 401.6ms inference, 1.0ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_090001.jpg: 448x640 1 FL, 417.1ms
Speed: 4.4ms preprocess, 417.1ms inference, 1.2ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_091501.jpg: 448x640 1 W, 487.1ms
Speed: 4.4ms preprocess, 487.1ms inference, 1.4ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_093001.jpg: 448x640 (no detections), 411.2ms
Speed: 3.6ms preprocess, 411.2ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_094502.jpg: 448x640 1 W, 422.9ms
Speed: 2.9ms preprocess, 422.9ms inference, 1.4ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_100001.jpg: 448x640 (no detections), 394.5ms
Speed: 3.7ms preprocess, 394.5ms inference, 0.6ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_101501.jpg: 448x640 (no detections), 388.6ms
Speed: 3.6ms preprocess, 388.6ms inference, 0.8ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_103001.jpg: 448x640 (no detections), 395.8ms
Speed: 3.1ms preprocess, 395.8ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_104501.jpg: 448x640 (no detections), 372.8ms
Speed: 2.9ms preprocess, 372.8ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_110001.jpg: 448x640 1 R, 388.6ms
Speed: 3.3ms preprocess, 388.6ms inference, 1.1ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_111501.jpg: 448x640 (no detections), 389.5ms
Speed: 2.5ms preprocess, 389.5ms inference, 2.1ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_113001.jpg: 448x640 1 W, 418.4ms
Speed: 4.2ms preprocess, 418.4ms inference, 2.6ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_114501.jpg: 448x640 (no detections), 396.4ms
Speed: 2.4ms preprocess, 396.4ms inference, 0.9ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_120001.jpg: 448x640 (no detections), 399.9ms
Speed: 9.3ms preprocess, 399.9ms inference, 0.9ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_121501.jpg: 448x640 (no detections), 431.1ms
Speed: 4.4ms preprocess, 431.1ms inference, 0.9ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_123001.jpg: 448x640 (no detections), 434.9ms
Speed: 5.5ms preprocess, 434.9ms inference, 0.8ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_124501.jpg: 448x640 1 G, 393.8ms
Speed: 6.0ms preprocess, 393.8ms inference, 1.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_130001.jpg: 448x640 (no detections), 384.8ms
Speed: 3.1ms preprocess, 384.8ms inference, 1.1ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_131501.jpg: 448x640 (no detections), 429.2ms
Speed: 2.9ms preprocess, 429.2ms inference, 0.6ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_133001.jpg: 448x640 (no detections), 415.8ms
Speed: 5.0ms preprocess, 415.8ms inference, 0.9ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_134501.jpg: 448x640 (no detections), 427.8ms
Speed: 2.9ms preprocess, 427.8ms inference, 1.4ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_140001.jpg: 448x640 (no detections), 424.0ms
Speed: 4.3ms preprocess, 424.0ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_141501.jpg: 448x640 (no detections), 437.7ms
Speed: 4.2ms preprocess, 437.7ms inference, 0.6ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_143001.jpg: 448x640 (no detections), 438.6ms
Speed: 3.6ms preprocess, 438.6ms inference, 1.0ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_144501.jpg: 448x640 (no detections), 471.7ms
Speed: 3.3ms preprocess, 471.7ms inference, 1.2ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_150001.jpg: 448x640 (no detections), 450.4ms
Speed: 3.7ms preprocess, 450.4ms inference, 0.8ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_151501.jpg: 448x640 (no detections), 421.9ms

In [2]:
from ultralytics import YOLO
import pandas as pd
import os

# Load YOLO model
model = YOLO("best.pt")   # your trained model

image_folder = r"F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images"  # folder containing images

results_list = []

for img in os.listdir(image_folder):
    
    img_path = os.path.join(image_folder, img)

    results = model(img_path)

    class_counts = {}
    total = 0

    for r in results:
        boxes = r.boxes.cls.tolist()

        for cls in boxes:
            class_name = model.names[int(cls)]

            if class_name not in class_counts:
                class_counts[class_name] = 0

            class_counts[class_name] += 1
            total += 1

    row = {"image_name": img, "total_objects": total}

    for k, v in class_counts.items():
        row[k] = v

    results_list.append(row)

# df = pd.DataFrame(results_list)

# # Fill missing class counts with 0
# df = df.fillna(0)

# df.to_excel("yolo_results.xlsx", index=False)

# print("Results saved to yolo_results.xlsx")

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-12_163001.jpg: 448x640 (no detections), 308.7ms
Speed: 6.1ms preprocess, 308.7ms inference, 1.1ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-12_164501.jpg: 448x640 1 G, 283.4ms
Speed: 2.9ms preprocess, 283.4ms inference, 1.4ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-12_170001.jpg: 448x640 1 G, 272.3ms
Speed: 1.7ms preprocess, 272.3ms inference, 1.0ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-12_171501.jpg: 448x640 1 P, 263.9ms
Speed: 1.9ms preprocess, 263.9ms inference, 0.8ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_063001.jpg: 448x640 1 R, 264.4ms
Speed: 1.8ms preprocess, 264.4ms inference, 0.9ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_064501.jpg: 448x640 (no detections), 262.2ms
Speed: 1.9ms preprocess, 262.2ms inference, 0.5ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_070001.jpg: 448x640 1 G, 264.3ms
Speed: 1.5ms preprocess, 264.3ms inference, 0.8ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_071501.jpg: 448x640 (no detections), 258.3ms
Speed: 2.1ms preprocess, 258.3ms inference, 0.6ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_073001.jpg: 448x640 (no detections), 261.3ms
Speed: 2.5ms preprocess, 261.3ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_074501.jpg: 448x640 1 FL, 2 Ws, 252.2ms
Speed: 2.2ms preprocess, 252.2ms inference, 1.0ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_080001.jpg: 448x640 1 G, 1 W, 244.3ms
Speed: 1.5ms preprocess, 244.3ms inference, 0.9ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_081501.jpg: 448x640 (no detections), 270.0ms
Speed: 2.4ms preprocess, 270.0ms inference, 1.1ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_083001.jpg: 448x640 1 FL, 242.9ms
Speed: 1.6ms preprocess, 242.9ms inference, 1.0ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_084501.jpg: 448x640 (no detections), 250.7ms
Speed: 1.8ms preprocess, 250.7ms inference, 0.5ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_090001.jpg: 448x640 (no detections), 262.2ms
Speed: 1.7ms preprocess, 262.2ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_091501.jpg: 448x640 1 W, 264.8ms
Speed: 2.1ms preprocess, 264.8ms inference, 0.9ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_093001.jpg: 448x640 (no detections), 261.4ms
Speed: 2.0ms preprocess, 261.4ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_094501.jpg: 448x640 (no detections), 278.7ms
Speed: 2.9ms preprocess, 278.7ms inference, 0.6ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_100001.jpg: 448x640 (no detections), 267.6ms
Speed: 2.2ms preprocess, 267.6ms inference, 0.5ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_101501.jpg: 448x640 (no detections), 282.2ms
Speed: 1.8ms preprocess, 282.2ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_103001.jpg: 448x640 (no detections), 261.1ms
Speed: 1.9ms preprocess, 261.1ms inference, 0.6ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_104501.jpg: 448x640 2 Rs, 259.1ms
Speed: 2.0ms preprocess, 259.1ms inference, 0.9ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_110001.jpg: 448x640 (no detections), 253.5ms
Speed: 1.9ms preprocess, 253.5ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_111501.jpg: 448x640 (no detections), 269.2ms
Speed: 2.1ms preprocess, 269.2ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_113001.jpg: 448x640 1 W, 278.0ms
Speed: 2.1ms preprocess, 278.0ms inference, 1.0ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_114501.jpg: 448x640 (no detections), 290.7ms
Speed: 4.4ms preprocess, 290.7ms inference, 0.6ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_120001.jpg: 448x640 (no detections), 256.6ms
Speed: 2.2ms preprocess, 256.6ms inference, 0.9ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_121501.jpg: 448x640 1 W, 266.7ms
Speed: 2.7ms preprocess, 266.7ms inference, 1.0ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_123001.jpg: 448x640 (no detections), 268.5ms
Speed: 2.7ms preprocess, 268.5ms inference, 0.6ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_124501.jpg: 448x640 (no detections), 277.8ms
Speed: 2.6ms preprocess, 277.8ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_130001.jpg: 448x640 (no detections), 274.2ms
Speed: 1.8ms preprocess, 274.2ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_131501.jpg: 448x640 (no detections), 265.7ms
Speed: 1.7ms preprocess, 265.7ms inference, 0.6ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_133001.jpg: 448x640 (no detections), 317.2ms
Speed: 2.1ms preprocess, 317.2ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_134501.jpg: 448x640 (no detections), 317.4ms
Speed: 2.4ms preprocess, 317.4ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_140001.jpg: 448x640 (no detections), 299.8ms
Speed: 1.8ms preprocess, 299.8ms inference, 0.9ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_141501.jpg: 448x640 (no detections), 310.2ms
Speed: 7.5ms preprocess, 310.2ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_143001.jpg: 448x640 (no detections), 269.1ms
Speed: 2.5ms preprocess, 269.1ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_144501.jpg: 448x640 (no detections), 261.2ms
Speed: 2.2ms preprocess, 261.2ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_150001.jpg: 448x640 (no detections), 277.3ms
Speed: 1.9ms preprocess, 277.3ms inference, 0.6ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_151502.jpg: 448x640 (no detections), 270.1ms
Speed: 1.8ms preprocess, 270.1ms inference, 0.5ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_153001.jpg: 448x640 1 R, 270.5ms
Speed: 2.4ms preprocess, 270.5ms inference, 1.1ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_154501.jpg: 448x640 (no detections), 263.9ms
Speed: 2.0ms preprocess, 263.9ms inference, 0.6ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_160001.jpg: 448x640 1 W, 270.3ms
Speed: 2.4ms preprocess, 270.3ms inference, 1.0ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_161501.jpg: 448x640 2 Ws, 270.1ms
Speed: 2.1ms preprocess, 270.1ms inference, 1.3ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_163001.jpg: 448x640 1 G, 261.1ms
Speed: 2.0ms preprocess, 261.1ms inference, 1.2ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_164501.jpg: 448x640 (no detections), 278.9ms
Speed: 2.4ms preprocess, 278.9ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-13_170001.jpg: 448x640 (no detections), 275.3ms
Speed: 2.0ms preprocess, 275.3ms inference, 0.6ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_074501.jpg: 448x640 1 W, 271.3ms
Speed: 2.1ms preprocess, 271.3ms inference, 1.2ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_080001.jpg: 448x640 1 W, 277.0ms
Speed: 2.2ms preprocess, 277.0ms inference, 0.9ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_081501.jpg: 448x640 (no detections), 271.3ms
Speed: 2.1ms preprocess, 271.3ms inference, 0.6ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_083001.jpg: 448x640 (no detections), 270.4ms
Speed: 2.2ms preprocess, 270.4ms inference, 0.8ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_084501.jpg: 448x640 1 FL, 1 W, 271.2ms
Speed: 1.9ms preprocess, 271.2ms inference, 1.4ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_090001.jpg: 448x640 1 FL, 285.4ms
Speed: 1.7ms preprocess, 285.4ms inference, 1.2ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_091501.jpg: 448x640 1 W, 274.6ms
Speed: 1.9ms preprocess, 274.6ms inference, 1.0ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_093001.jpg: 448x640 (no detections), 272.2ms
Speed: 2.1ms preprocess, 272.2ms inference, 0.8ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_094502.jpg: 448x640 1 W, 275.5ms
Speed: 1.7ms preprocess, 275.5ms inference, 0.8ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_100001.jpg: 448x640 (no detections), 275.5ms
Speed: 2.2ms preprocess, 275.5ms inference, 0.8ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_101501.jpg: 448x640 (no detections), 279.5ms
Speed: 1.8ms preprocess, 279.5ms inference, 0.6ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_103001.jpg: 448x640 (no detections), 286.6ms
Speed: 1.9ms preprocess, 286.6ms inference, 0.9ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_104501.jpg: 448x640 (no detections), 340.7ms
Speed: 2.1ms preprocess, 340.7ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_110001.jpg: 448x640 1 R, 288.2ms
Speed: 2.5ms preprocess, 288.2ms inference, 1.0ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_111501.jpg: 448x640 (no detections), 278.9ms
Speed: 2.4ms preprocess, 278.9ms inference, 0.8ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_113001.jpg: 448x640 1 W, 284.3ms
Speed: 1.9ms preprocess, 284.3ms inference, 1.3ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_114501.jpg: 448x640 (no detections), 285.4ms
Speed: 2.2ms preprocess, 285.4ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_120001.jpg: 448x640 (no detections), 283.2ms
Speed: 2.0ms preprocess, 283.2ms inference, 0.5ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_121501.jpg: 448x640 (no detections), 275.7ms
Speed: 2.5ms preprocess, 275.7ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_123001.jpg: 448x640 (no detections), 272.9ms
Speed: 2.3ms preprocess, 272.9ms inference, 0.6ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_124501.jpg: 448x640 1 G, 272.2ms
Speed: 1.7ms preprocess, 272.2ms inference, 1.0ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_130001.jpg: 448x640 (no detections), 303.1ms
Speed: 2.5ms preprocess, 303.1ms inference, 0.8ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_131501.jpg: 448x640 (no detections), 312.9ms
Speed: 2.2ms preprocess, 312.9ms inference, 0.8ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_133001.jpg: 448x640 (no detections), 374.5ms
Speed: 2.7ms preprocess, 374.5ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_134501.jpg: 448x640 (no detections), 377.9ms
Speed: 2.5ms preprocess, 377.9ms inference, 0.9ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_140001.jpg: 448x640 (no detections), 278.2ms
Speed: 1.9ms preprocess, 278.2ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_141501.jpg: 448x640 (no detections), 282.2ms
Speed: 2.6ms preprocess, 282.2ms inference, 0.6ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_143001.jpg: 448x640 (no detections), 275.0ms
Speed: 1.7ms preprocess, 275.0ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_144501.jpg: 448x640 (no detections), 269.6ms
Speed: 1.8ms preprocess, 269.6ms inference, 0.7ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_150001.jpg: 448x640 (no detections), 283.5ms
Speed: 2.1ms preprocess, 283.5ms inference, 0.6ms postprocess per image at shape (1, 3, 448, 640)

image 1/1 F:\strwaberry images\back row upated with text\Cropped_Images\down_2\preprocessed_images\citra_2025-12-14_151501.jpg: 448x640 (no detections), 276.4ms

FileNotFoundError: file 'citra_2025-12-12_163001.jpg' does not exist

In [3]:
results_list

[{'image_name': 'citra_2025-12-12_163001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-12_164501.jpg', 'total_objects': 1, 'G': 1},
 {'image_name': 'citra_2025-12-12_170001.jpg', 'total_objects': 1, 'G': 1},
 {'image_name': 'citra_2025-12-12_171501.jpg', 'total_objects': 1, 'P': 1},
 {'image_name': 'citra_2025-12-13_063001.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-13_064501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_070001.jpg', 'total_objects': 1, 'G': 1},
 {'image_name': 'citra_2025-12-13_071501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_073001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_074501.jpg',
  'total_objects': 3,
  'FL': 1,
  'W': 2},
 {'image_name': 'citra_2025-12-13_080001.jpg',
  'total_objects': 2,
  'W': 1,
  'G': 1},
 {'image_name': 'citra_2025-12-13_081501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_083001.jpg', 'total_objects': 1, 'FL': 1},
 {'image_name': 'citra_2025-12-13_084501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_090001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_091501.jpg', 'total_objects': 1, 'W': 1},
 {'image_name': 'citra_2025-12-13_093001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_094501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_100001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_101501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_103001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_104501.jpg', 'total_objects': 2, 'R': 2},
 {'image_name': 'citra_2025-12-13_110001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_111501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_113001.jpg', 'total_objects': 1, 'W': 1},
 {'image_name': 'citra_2025-12-13_114501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_120001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_121501.jpg', 'total_objects': 1, 'W': 1},
 {'image_name': 'citra_2025-12-13_123001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_124501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_130001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_131501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_133001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_134501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_140001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_141501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_143001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_144501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_150001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_151502.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_153001.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-13_154501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_160001.jpg', 'total_objects': 1, 'W': 1},
 {'image_name': 'citra_2025-12-13_161501.jpg', 'total_objects': 2, 'W': 2},
 {'image_name': 'citra_2025-12-13_163001.jpg', 'total_objects': 1, 'G': 1},
 {'image_name': 'citra_2025-12-13_164501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-13_170001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_074501.jpg', 'total_objects': 1, 'W': 1},
 {'image_name': 'citra_2025-12-14_080001.jpg', 'total_objects': 1, 'W': 1},
 {'image_name': 'citra_2025-12-14_081501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_083001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_084501.jpg',
  'total_objects': 2,
  'W': 1,
  'FL': 1},
 {'image_name': 'citra_2025-12-14_090001.jpg', 'total_objects': 1, 'FL': 1},
 {'image_name': 'citra_2025-12-14_091501.jpg', 'total_objects': 1, 'W': 1},
 {'image_name': 'citra_2025-12-14_093001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_094502.jpg', 'total_objects': 1, 'W': 1},
 {'image_name': 'citra_2025-12-14_100001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_101501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_103001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_104501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_110001.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-14_111501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_113001.jpg', 'total_objects': 1, 'W': 1},
 {'image_name': 'citra_2025-12-14_114501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_120001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_121501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_123001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_124501.jpg', 'total_objects': 1, 'G': 1},
 {'image_name': 'citra_2025-12-14_130001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_131501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_133001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_134501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_140001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_141501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_143001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_144501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_150001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_151501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_153001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_154502.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_160001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_161501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-14_163001.jpg',
  'total_objects': 2,
  'P': 1,
  'G': 1},
 {'image_name': 'citra_2025-12-14_164501.jpg', 'total_objects': 2, 'G': 2},
 {'image_name': 'citra_2025-12-14_170002.jpg', 'total_objects': 1, 'P': 1},
 {'image_name': 'citra_2025-12-14_171501.jpg', 'total_objects': 1, 'P': 1},
 {'image_name': 'citra_2025-12-15_063001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-15_064501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-15_070001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-15_071501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-15_073001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-15_074501.jpg', 'total_objects': 1, 'P': 1},
 {'image_name': 'citra_2025-12-15_080001.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-15_081501.jpg',
  'total_objects': 2,
  'P': 1,
  'R': 1},
 {'image_name': 'citra_2025-12-15_083001.jpg',
  'total_objects': 2,
  'R': 1,
  'P': 1},
 {'image_name': 'citra_2025-12-15_084501.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-15_090001.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-15_091501.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-15_093001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-15_094501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-15_100001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-15_101501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-15_103001.jpg', 'total_objects': 2, 'R': 2},
 {'image_name': 'citra_2025-12-15_104501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-15_110001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-15_111501.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-15_113001.jpg',
  'total_objects': 3,
  'G': 1,
  'P': 1,
  'R': 1},
 {'image_name': 'citra_2025-12-15_114501.jpg', 'total_objects': 2, 'R': 2},
 {'image_name': 'citra_2025-12-15_120001.jpg', 'total_objects': 2, 'R': 2},
 {'image_name': 'citra_2025-12-15_121501.jpg', 'total_objects': 2, 'R': 2},
 {'image_name': 'citra_2025-12-15_123001.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-15_124501.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-15_130001.jpg',
  'total_objects': 2,
  'R': 1,
  'P': 1},
 {'image_name': 'citra_2025-12-15_131501.jpg',
  'total_objects': 2,
  'R': 1,
  'W': 1},
 {'image_name': 'citra_2025-12-15_133001.jpg',
  'total_objects': 2,
  'R': 1,
  'P': 1},
 {'image_name': 'citra_2025-12-15_134501.jpg',
  'total_objects': 3,
  'R': 1,
  'G': 1,
  'P': 1},
 {'image_name': 'citra_2025-12-15_140001.jpg',
  'total_objects': 3,
  'P': 1,
  'R': 1,
  'G': 1},
 {'image_name': 'citra_2025-12-15_141501.jpg',
  'total_objects': 2,
  'P': 1,
  'R': 1},
 {'image_name': 'citra_2025-12-15_143001.jpg',
  'total_objects': 2,
  'P': 1,
  'R': 1},
 {'image_name': 'citra_2025-12-15_144501.jpg',
  'total_objects': 2,
  'P': 1,
  'R': 1},
 {'image_name': 'citra_2025-12-15_150001.jpg',
  'total_objects': 3,
  'P': 1,
  'R': 1,
  'G': 1},
 {'image_name': 'citra_2025-12-15_151501.jpg',
  'total_objects': 3,
  'P': 1,
  'R': 1,
  'G': 1},
 {'image_name': 'citra_2025-12-15_153001.jpg',
  'total_objects': 2,
  'R': 1,
  'P': 1},
 {'image_name': 'citra_2025-12-15_154501.jpg',
  'total_objects': 2,
  'R': 1,
  'P': 1},
 {'image_name': 'citra_2025-12-15_160001.jpg',
  'total_objects': 2,
  'P': 1,
  'R': 1},
 {'image_name': 'citra_2025-12-15_161501.jpg',
  'total_objects': 3,
  'P': 1,
  'G': 1,
  'R': 1},
 {'image_name': 'citra_2025-12-15_163001.jpg',
  'total_objects': 2,
  'P': 1,
  'R': 1},
 {'image_name': 'citra_2025-12-15_164501.jpg',
  'total_objects': 2,
  'P': 1,
  'R': 1},
 {'image_name': 'citra_2025-12-15_170001.jpg',
  'total_objects': 3,
  'P': 1,
  'R': 1,
  'G': 1},
 {'image_name': 'citra_2025-12-15_171501.jpg',
  'total_objects': 2,
  'P': 1,
  'R': 1},
 {'image_name': 'citra_2025-12-16_063001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-16_064501.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-16_070001.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-16_071501.jpg', 'total_objects': 2, 'R': 2},
 {'image_name': 'citra_2025-12-16_073001.jpg', 'total_objects': 2, 'R': 2},
 {'image_name': 'citra_2025-12-16_074501.jpg', 'total_objects': 2, 'R': 2},
 {'image_name': 'citra_2025-12-16_080001.jpg', 'total_objects': 0},
 {'image_name': 'citra_2025-12-16_081501.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-16_083001.jpg', 'total_objects': 1, 'G': 1},
 {'image_name': 'citra_2025-12-16_084501.jpg',
  'total_objects': 3,
  'G': 2,
  'R': 1},
 {'image_name': 'citra_2025-12-16_090001.jpg',
  'total_objects': 2,
  'G': 1,
  'R': 1},
 {'image_name': 'citra_2025-12-16_091501.jpg',
  'total_objects': 2,
  'G': 1,
  'R': 1},
 {'image_name': 'citra_2025-12-16_093001.jpg',
  'total_objects': 3,
  'R': 1,
  'G': 2},
 {'image_name': 'citra_2025-12-16_094501.jpg',
  'total_objects': 2,
  'G': 1,
  'R': 1},
 {'image_name': 'citra_2025-12-16_100001.jpg', 'total_objects': 2, 'R': 2},
 {'image_name': 'citra_2025-12-16_101501.jpg', 'total_objects': 1, 'P': 1},
 {'image_name': 'citra_2025-12-16_103001.jpg',
  'total_objects': 3,
  'R': 2,
  'P': 1},
 {'image_name': 'citra_2025-12-16_104501.jpg', 'total_objects': 2, 'R': 2},
 {'image_name': 'citra_2025-12-16_110001.jpg', 'total_objects': 4, 'R': 4},
 {'image_name': 'citra_2025-12-16_111501.jpg', 'total_objects': 2, 'R': 2},
 {'image_name': 'citra_2025-12-16_113001.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-16_114501.jpg', 'total_objects': 2, 'R': 2},
 {'image_name': 'citra_2025-12-16_120001.jpg', 'total_objects': 2, 'R': 2},
 {'image_name': 'citra_2025-12-16_121501.jpg', 'total_objects': 2, 'R': 2},
 {'image_name': 'citra_2025-12-16_123001.jpg', 'total_objects': 2, 'R': 2},
 {'image_name': 'citra_2025-12-16_124501.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-16_130001.jpg', 'total_objects': 2, 'R': 2},
 {'image_name': 'citra_2025-12-16_131501.jpg', 'total_objects': 2, 'R': 2},
 {'image_name': 'citra_2025-12-16_133001.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-16_134501.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-16_140001.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-16_141501.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-16_143001.jpg',
  'total_objects': 3,
  'P': 1,
  'R': 2},
 {'image_name': 'citra_2025-12-16_144501.jpg',
  'total_objects': 4,
  'G': 2,
  'R': 1,
  'P': 1},
 {'image_name': 'citra_2025-12-16_150001.jpg',
  'total_objects': 3,
  'G': 2,
  'R': 1},
 {'image_name': 'citra_2025-12-16_151501.jpg',
  'total_objects': 2,
  'R': 1,
  'G': 1},
 {'image_name': 'citra_2025-12-16_153001.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-16_154501.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-16_160001.jpg',
  'total_objects': 4,
  'W': 2,
  'R': 2},
 {'image_name': 'citra_2025-12-16_161501.jpg',
  'total_objects': 2,
  'R': 1,
  'W': 1},
 {'image_name': 'citra_2025-12-16_163001.jpg',
  'total_objects': 2,
  'R': 1,
  'P': 1},
 {'image_name': 'citra_2025-12-16_164501.jpg',
  'total_objects': 4,
  'G': 3,
  'R': 1},
 {'image_name': 'citra_2025-12-16_170001.jpg',
  'total_objects': 3,
  'G': 1,
  'R': 1,
  'P': 1},
 {'image_name': 'citra_2025-12-16_171501.jpg',
  'total_objects': 3,
  'R': 1,
  'P': 1,
  'G': 1},
 {'image_name': 'citra_2025-12-17_083001.jpg',
  'total_objects': 3,
  'R': 2,
  'G': 1},
 {'image_name': 'citra_2025-12-17_084501.jpg',
  'total_objects': 3,
  'R': 2,
  'G': 1},
 {'image_name': 'citra_2025-12-17_090001.jpg',
  'total_objects': 2,
  'R': 1,
  'G': 1},
 {'image_name': 'citra_2025-12-17_091501.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-17_093001.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-17_094501.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-17_100001.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-17_101501.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-17_103001.jpg', 'total_objects': 2, 'R': 2},
 {'image_name': 'citra_2025-12-17_104501.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-17_110001.jpg',
  'total_objects': 2,
  'R': 1,
  'W': 1},
 {'image_name': 'citra_2025-12-17_111501.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-17_113001.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-17_114501.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-17_120001.jpg',
  'total_objects': 2,
  'R': 1,
  'G': 1},
 {'image_name': 'citra_2025-12-17_121501.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-17_123001.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-17_124501.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-17_130001.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-17_131501.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-17_133001.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-17_134501.jpg',
  'total_objects': 2,
  'R': 1,
  'G': 1},
 {'image_name': 'citra_2025-12-17_140001.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-17_141501.jpg',
  'total_objects': 2,
  'R': 1,
  'G': 1},
 {'image_name': 'citra_2025-12-17_143001.jpg',
  'total_objects': 2,
  'R': 1,
  'G': 1},
 {'image_name': 'citra_2025-12-17_144501.jpg',
  'total_objects': 2,
  'R': 1,
  'G': 1},
 {'image_name': 'citra_2025-12-17_150001.jpg',
  'total_objects': 3,
  'R': 1,
  'G': 2},
 {'image_name': 'citra_2025-12-17_151501.jpg',
  'total_objects': 3,
  'R': 1,
  'G': 2},
 {'image_name': 'citra_2025-12-17_153001.jpg',
  'total_objects': 3,
  'R': 1,
  'G': 2},
 {'image_name': 'citra_2025-12-17_154501.jpg',
  'total_objects': 2,
  'R': 1,
  'G': 1},
 {'image_name': 'citra_2025-12-17_160001.jpg',
  'total_objects': 2,
  'R': 1,
  'G': 1},
 {'image_name': 'citra_2025-12-17_161501.jpg',
  'total_objects': 3,
  'R': 1,
  'G': 2},
 {'image_name': 'citra_2025-12-17_163001.jpg',
  'total_objects': 3,
  'R': 1,
  'G': 2},
 {'image_name': 'citra_2025-12-17_164501.jpg',
  'total_objects': 4,
  'R': 1,
  'G': 2,
  'FL': 1},
 {'image_name': 'citra_2025-12-17_170001.jpg',
  'total_objects': 3,
  'R': 1,
  'G': 2},
 {'image_name': 'citra_2025-12-17_171501.jpg',
  'total_objects': 3,
  'R': 1,
  'G': 2},
 {'image_name': 'citra_2025-12-18_064501.jpg',
  'total_objects': 2,
  'R': 1,
  'G': 1},
 {'image_name': 'citra_2025-12-18_070001.jpg',
  'total_objects': 2,
  'R': 1,
  'G': 1},
 {'image_name': 'citra_2025-12-18_071501.jpg',
  'total_objects': 3,
  'R': 1,
  'G': 2},
 {'image_name': 'citra_2025-12-18_073001.jpg', 'total_objects': 2, 'R': 2},
 {'image_name': 'citra_2025-12-18_074501.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-18_080001.jpg',
  'total_objects': 3,
  'G': 2,
  'R': 1},
 {'image_name': 'citra_2025-12-18_081501.jpg',
  'total_objects': 2,
  'R': 1,
  'G': 1},
 {'image_name': 'citra_2025-12-18_083001.jpg',
  'total_objects': 3,
  'R': 2,
  'G': 1},
 {'image_name': 'citra_2025-12-18_084501.jpg',
  'total_objects': 2,
  'R': 1,
  'G': 1},
 {'image_name': 'citra_2025-12-18_090001.jpg', 'total_objects': 2, 'R': 2},
 {'image_name': 'citra_2025-12-18_091501.jpg',
  'total_objects': 3,
  'R': 2,
  'G': 1},
 {'image_name': 'citra_2025-12-18_093001.jpg',
  'total_objects': 2,
  'G': 1,
  'R': 1},
 {'image_name': 'citra_2025-12-18_094502.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-18_100001.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-18_101501.jpg',
  'total_objects': 2,
  'R': 1,
  'G': 1},
 {'image_name': 'citra_2025-12-18_103001.jpg',
  'total_objects': 2,
  'R': 1,
  'W': 1},
 {'image_name': 'citra_2025-12-18_104501.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-18_110001.jpg',
  'total_objects': 2,
  'R': 1,
  'G': 1},
 {'image_name': 'citra_2025-12-18_111501.jpg',
  'total_objects': 3,
  'R': 2,
  'G': 1},
 {'image_name': 'citra_2025-12-18_113001.jpg',
  'total_objects': 6,
  'R': 1,
  'G': 4,
  'W': 1},
 {'image_name': 'citra_2025-12-18_114501.jpg',
  'total_objects': 4,
  'G': 3,
  'R': 1},
 {'image_name': 'citra_2025-12-18_120001.jpg',
  'total_objects': 6,
  'G': 3,
  'R': 2,
  'W': 1},
 {'image_name': 'citra_2025-12-18_121501.jpg',
  'total_objects': 4,
  'R': 2,
  'G': 2},
 {'image_name': 'citra_2025-12-18_123001.jpg',
  'total_objects': 6,
  'R': 2,
  'G': 3,
  'W': 1},
 {'image_name': 'citra_2025-12-18_124501.jpg',
  'total_objects': 7,
  'R': 1,
  'G': 5,
  'W': 1},
 {'image_name': 'citra_2025-12-18_130001.jpg',
  'total_objects': 6,
  'R': 2,
  'W': 1,
  'G': 3},
 {'image_name': 'citra_2025-12-18_131501.jpg',
  'total_objects': 3,
  'G': 2,
  'R': 1},
 {'image_name': 'citra_2025-12-18_133001.jpg',
  'total_objects': 5,
  'R': 1,
  'W': 2,
  'G': 2},
 {'image_name': 'citra_2025-12-18_134501.jpg',
  'total_objects': 6,
  'R': 3,
  'G': 2,
  'W': 1},
 {'image_name': 'citra_2025-12-18_140001.jpg',
  'total_objects': 4,
  'G': 2,
  'R': 1,
  'W': 1},
 {'image_name': 'citra_2025-12-18_141501.jpg', 'total_objects': 1, 'R': 1},
 {'image_name': 'citra_2025-12-18_143001.jpg',
  'total_objects': 2,
  'R': 1,
  'G': 1},
 {'image_name': 'citra_2025-12-18_144501.jpg',
  'total_objects': 3,
  'R': 2,
  'G': 1},
 {'image_name': 'citra_2025-12-18_150001.jpg',
  'total_objects': 4,
  'R': 2,
  'G': 1,
  'FL': 1},
 {'image_name': 'citra_2025-12-18_151501.jpg',
  'total_objects': 3,
  'R': 2,
  'G': 1},
 {'image_name': 'citra_2025-12-18_153001.jpg',
  'total_objects': 2,
  'R': 1,
  'G': 1},
 {'image_name': 'citra_2025-12-18_154501.jpg',
  'total_objects': 4,
  'R': 3,
  'G': 1},
 {'image_name': 'citra_2025-12-18_160001.jpg',
  'total_objects': 3,
  'R': 1,
  'G': 1,
  'W': 1},
 {'image_name': 'citra_2025-12-18_161501.jpg',
  'total_objects': 2,
  'R': 1,
  'G': 1},
 {'image_name': 'citra_2025-12-18_163001.jpg',
  'total_objects': 4,
  'R': 2,
  'G': 1,
  'W': 1},

In [ ]:
df = pd.DataFrame(results_list)

# Fill missing class counts with 0
df = df.fillna(0)
df
df.to_excel("yolo_results_back.xlsx", index=False)

print("Results saved to yolo_results.xlsx")