In [40]:
import pandas as pd

df=pd.read_excel("F:\strwaberry images\Front_images_mapped_images_down_1.xlsx")

In [5]:
df = df.dropna(subset=["image_name"])
df.to_excel("F:\strwaberry images\Front_row_dataset_new\weather_data.xlsx", index=False)
df

,Station ID,Date Time,Soil Temp (C),Temp @ 60cm (C),Temp @ 2m (C),Temp @ 10m (C),Relative Humidity (%),Dew Point Temp (C),Rainfall Amount (in),Wind Speed (mph),Wind Direction (deg),Solar Radiation (w/m2),image_name
59,260,1969-12-31 19:00:46.004,12.48,2.31,3.61,3.32,94.00,2.74,0.0,1.51,100.20,0.01,citra_2025-12-13_060001.jpg
60,260,1969-12-31 19:00:46.004,12.43,2.39,3.44,3.28,94.00,2.57,0.0,1.45,92.80,0.02,citra_2025-12-13_061501.jpg
61,260,1969-12-31 19:00:46.004,12.38,2.09,3.40,3.28,94.00,2.53,0.0,0.98,87.50,0.01,citra_2025-12-13_063001.jpg
62,260,1969-12-31 19:00:46.004,12.33,2.02,3.36,3.34,94.00,2.49,0.0,1.22,100.10,0.02,citra_2025-12-13_064501.jpg
63,260,1969-12-31 19:00:46.004,12.29,2.04,3.24,3.42,94.00,2.37,0.0,1.07,75.38,0.18,citra_2025-12-13_070001.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...
844,260,1969-12-31 19:00:46.012,12.44,14.03,15.15,13.73,86.50,12.91,0.0,1.82,41.25,460.30,citra_2025-12-21_101501.jpg
845,260,1969-12-31 19:00:46.012,12.46,16.09,16.92,15.31,68.58,11.11,0.0,3.51,31.14,486.90,citra_2025-12-21_103001.jpg
846,260,1969-12-31 19:00:46.012,12.49,17.40,17.72,16.29,65.73,11.23,0.0,4.46,35.11,508.20,citra_2025-12-21_104501.jpg
847,260,1969-12-31 19:00:46.012,12.54,18.48,18.97,17.27,62.68,11.70,0.0,3.78,44.05,532.50,citra_2025-12-21_110001.jpg
848,260,1969-12-31 19:00:46.012,12.61,19.00,19.24,17.75,62.26,11.85,0.0,4.47,61.62,550.00,citra_2025-12-21_111501.jpg

In [83]:
##mapped weather with all the images
import os
import pandas as pd
final_excel_path=r"F:\strwaberry images\Front_row_dataset_new\front_row_top5.xlsx"
# paths
excel_path = r"F:\strwaberry images\Front_row_dataset_new\weather_data_down1.xlsx"
image_folder = r"F:\strwaberry images\Front_row_with_text\Cropped_Images_front\top_5\preprocessed_images_lighting_removal_top_5"

# string to remove
remove_prefix = "front_row_top5"

# read excel
df = pd.read_excel(excel_path)

# make lookup dictionary
available_images = os.listdir(image_folder)

clean_map = {}
unmatched_folder_images = []

for img in available_images:
    if img.startswith(remove_prefix):
        cleaned = img.replace(remove_prefix, "")
        clean_map[cleaned] = img
    else:
        unmatched_folder_images.append(img)

# match with excel
new_names = []
missing_in_folder = []

for name in df["image_name"]:
    if name in clean_map:
        new_names.append(clean_map[name])
    else:
        new_names.append(None)
        missing_in_folder.append(name)

# add new column
df["new_image_name"] = new_names

# save output
output_path = f"{remove_prefix}.xlsx"
# df.to_excel(output_path, index=False)

print("Matching completed")
print("Output saved:", output_path)

print("\nImages missing in folder:")
for m in missing_in_folder:
    print(m)

print("\nImages in folder but not used:")
unused = set(clean_map.values()) - set(df["new_image_name"].dropna())
for u in unused:
    print(u)

Matching completed
Output saved: front_row_top5.xlsx

Images missing in folder:

Images in folder but not used:
front_row_top5citra_2025-12-12_150001.jpg
front_row_top5citra_2025-12-12_144501.jpg
front_row_top5citra_2025-11-27_133401.jpg
front_row_top5citra_2025-11-27_133501.jpg

In [84]:
import re 
# function to extract date & time
def extract_datetime(filename):
    match = re.search(r'citra_(\d{4}-\d{2}-\d{2})_(\d{6})', filename)
    if match:
        date = match.group(1)
        time_raw = match.group(2)
        time = f"{time_raw[:2]}:{time_raw[2:4]}:{time_raw[4:]}"
        return pd.Series([date, time])
    return pd.Series([None, None])

# create new columns
df[["date", "time"]] = df["new_image_name"].apply(extract_datetime)

In [85]:
df

,Unnamed: 0.1,Unnamed: 0,Station ID,Date Time,Soil Temp (C),Temp @ 60cm (C),Temp @ 2m (C),Temp @ 10m (C),Relative Humidity (%),Dew Point Temp (C),...,new_image_name,date,time,green_pixels,Tmax_x,Tmin_x,GDD_x,Tmax_y,Tmin_y,GDD_y
0,0,0,260,1969-12-31 19:00:46.004,12.48,2.31,3.61,3.32,94.00,2.74,...,front_row_top5citra_2025-12-13_060001.jpg,2025-12-13,06:00:01,190100,24.94,7.0,8.97,24.94,7.0,8.97
1,1,1,260,1969-12-31 19:00:46.004,12.43,2.39,3.44,3.28,94.00,2.57,...,front_row_top5citra_2025-12-13_061501.jpg,2025-12-13,06:15:01,182467,24.94,7.0,8.97,24.94,7.0,8.97
2,2,2,260,1969-12-31 19:00:46.004,12.38,2.09,3.40,3.28,94.00,2.53,...,front_row_top5citra_2025-12-13_063001.jpg,2025-12-13,06:30:01,173166,24.94,7.0,8.97,24.94,7.0,8.97
3,3,3,260,1969-12-31 19:00:46.004,12.33,2.02,3.36,3.34,94.00,2.49,...,front_row_top5citra_2025-12-13_064501.jpg,2025-12-13,06:45:01,170570,24.94,7.0,8.97,24.94,7.0,8.97
4,4,4,260,1969-12-31 19:00:46.004,12.29,2.04,3.24,3.42,94.00,2.37,...,front_row_top5citra_2025-12-13_070001.jpg,2025-12-13,07:00:01,168057,24.94,7.0,8.97,24.94,7.0,8.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,315,315,260,1969-12-31 19:00:46.012,12.44,14.03,15.15,13.73,86.50,12.91,...,front_row_top5citra_2025-12-21_101501.jpg,2025-12-21,10:15:01,159306,19.24,7.0,6.12,19.24,7.0,6.12
316,316,316,260,1969-12-31 19:00:46.012,12.46,16.09,16.92,15.31,68.58,11.11,...,front_row_top5citra_2025-12-21_103001.jpg,2025-12-21,10:30:01,168266,19.24,7.0,6.12,19.24,7.0,6.12
317,317,317,260,1969-12-31 19:00:46.012,12.49,17.40,17.72,16.29,65.73,11.23,...,front_row_top5citra_2025-12-21_104501.jpg,2025-12-21,10:45:01,171053,19.24,7.0,6.12,19.24,7.0,6.12
318,318,318,260,1969-12-31 19:00:46.012,12.54,18.48,18.97,17.27,62.68,11.70,...,front_row_top5citra_2025-12-21_110001.jpg,2025-12-21,11:00:01,158846,19.24,7.0,6.12,19.24,7.0,6.12
319,319,319,260,1969-12-31 19:00:46.012,12.61,19.00,19.24,17.75,62.26,11.85,...,front_row_top5citra_2025-12-21_111501.jpg,2025-12-21,11:15:01,161525,19.24,7.0,6.12,19.24,7.0,6.12

In [86]:
import cv2
import numpy as np
# import pandas as pd
from pathlib import Path
green_dict = {}

for path in Path(image_folder).glob("*.jpg"):

    img = cv2.imread(str(path))
    if img is None:
        continue

    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

    lower_green = np.array([35,40,40])
    upper_green = np.array([90,255,255])

    mask = cv2.inRange(hsv, lower_green, upper_green)

    kernel = np.ones((5,5),np.uint8)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)

    green_pixels = cv2.countNonZero(mask)

    green_dict[path.name] = green_pixels


# add green_pixels column using image_name
df["green_pixels"] = df["new_image_name"].map(green_dict)
# df_final.to_excel(base_path+"\\"+excel_name, index=False)
df

,Unnamed: 0.1,Unnamed: 0,Station ID,Date Time,Soil Temp (C),Temp @ 60cm (C),Temp @ 2m (C),Temp @ 10m (C),Relative Humidity (%),Dew Point Temp (C),...,new_image_name,date,time,green_pixels,Tmax_x,Tmin_x,GDD_x,Tmax_y,Tmin_y,GDD_y
0,0,0,260,1969-12-31 19:00:46.004,12.48,2.31,3.61,3.32,94.00,2.74,...,front_row_top5citra_2025-12-13_060001.jpg,2025-12-13,06:00:01,42895,24.94,7.0,8.97,24.94,7.0,8.97
1,1,1,260,1969-12-31 19:00:46.004,12.43,2.39,3.44,3.28,94.00,2.57,...,front_row_top5citra_2025-12-13_061501.jpg,2025-12-13,06:15:01,37677,24.94,7.0,8.97,24.94,7.0,8.97
2,2,2,260,1969-12-31 19:00:46.004,12.38,2.09,3.40,3.28,94.00,2.53,...,front_row_top5citra_2025-12-13_063001.jpg,2025-12-13,06:30:01,36504,24.94,7.0,8.97,24.94,7.0,8.97
3,3,3,260,1969-12-31 19:00:46.004,12.33,2.02,3.36,3.34,94.00,2.49,...,front_row_top5citra_2025-12-13_064501.jpg,2025-12-13,06:45:01,35484,24.94,7.0,8.97,24.94,7.0,8.97
4,4,4,260,1969-12-31 19:00:46.004,12.29,2.04,3.24,3.42,94.00,2.37,...,front_row_top5citra_2025-12-13_070001.jpg,2025-12-13,07:00:01,35577,24.94,7.0,8.97,24.94,7.0,8.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,315,315,260,1969-12-31 19:00:46.012,12.44,14.03,15.15,13.73,86.50,12.91,...,front_row_top5citra_2025-12-21_101501.jpg,2025-12-21,10:15:01,26298,19.24,7.0,6.12,19.24,7.0,6.12
316,316,316,260,1969-12-31 19:00:46.012,12.46,16.09,16.92,15.31,68.58,11.11,...,front_row_top5citra_2025-12-21_103001.jpg,2025-12-21,10:30:01,33535,19.24,7.0,6.12,19.24,7.0,6.12
317,317,317,260,1969-12-31 19:00:46.012,12.49,17.40,17.72,16.29,65.73,11.23,...,front_row_top5citra_2025-12-21_104501.jpg,2025-12-21,10:45:01,27423,19.24,7.0,6.12,19.24,7.0,6.12
318,318,318,260,1969-12-31 19:00:46.012,12.54,18.48,18.97,17.27,62.68,11.70,...,front_row_top5citra_2025-12-21_110001.jpg,2025-12-21,11:00:01,28207,19.24,7.0,6.12,19.24,7.0,6.12
319,319,319,260,1969-12-31 19:00:46.012,12.61,19.00,19.24,17.75,62.26,11.85,...,front_row_top5citra_2025-12-21_111501.jpg,2025-12-21,11:15:01,25687,19.24,7.0,6.12,19.24,7.0,6.12

In [87]:
# convert datetime
df["date"] = pd.to_datetime(df["date"])

# extract date
df["date"] = df["date"].dt.date

temp_col = "Temp @ 2m (C)"

# calculate daily Tmax and Tmin
daily = df.groupby("date")[temp_col].agg(["max","min"]).reset_index()
daily.columns = ["date","Tmax","Tmin"]

# GDD parameters
Tbase = 7
Tmax_cap = 30

# apply rules
daily["Tmax"] = daily["Tmax"].clip(upper=Tmax_cap)
daily["Tmin"] = daily["Tmin"].clip(lower=Tbase)

daily["GDD"] = ((daily["Tmax"] + daily["Tmin"]) / 2) - Tbase
daily["GDD"] = daily["GDD"].clip(lower=0)

# merge back into main dataset
df_final = df.merge(daily, on="date", how="left")
df_final.to_excel(final_excel_path)

In [88]:
##merge all the excels of the the folder into one excel
import pandas as pd
import os
from glob import glob

# folder containing multiple excel files
folder_path = r"F:\strwaberry images\front_row_dataset_new"

# output merged file
output_file = os.path.join(folder_path, "Front_row_merged_outpt.xlsx")

# get all excel files
excel_files = glob(os.path.join(folder_path, "*.xlsx"))

# remove temp files like ~$file.xlsx
excel_files = [f for f in excel_files if not os.path.basename(f).startswith("~$")]

# read and merge
df_list = [pd.read_excel(file) for file in excel_files]
merged_df = pd.concat(df_list, ignore_index=True)

# save merged file
merged_df.to_excel(output_file, index=False)

print("Merged file saved at:", output_file)

Merged file saved at: F:\strwaberry images\front_row_dataset_new\Front_row_merged_outpt.xlsx

In [90]:
import pandas as pd

excel_path = r"F:\strwaberry images\front_row_dataset_new\Front_row_merged_outpt.xlsx"   # your final merged excel

df = pd.read_excel(excel_path)

# mapping based on prefix inside new_image_name
plant_map = {
    "front_row_down1": 21,
    "front_row_down2": 22,
    "front_row_down3": 23,
    "front_row_down4": 24,
    "front_row_down5": 25,
    "front_row_top1": 11,
    "front_row_top3": 13,
    "front_row_top4": 14,
    "front_row_top5": 15
}

def assign_plant_id(name):
    name = str(name)
    for key, value in plant_map.items():
        if key in name:
            return value
    return None

# create new column
df["plant_id"] = df["new_image_name"].apply(assign_plant_id)

# save back
df.to_excel(excel_path, index=False)
df
print("plant_id column added")

plant_id column added